import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';
import type { TSchema } from 'typebox';
import { Value } from 'typebox/value';

import * as contracts from '../src/v3.ts';

const firstId = '00000000-0000-4000-8000-000000000001';
const secondId = '00000000-0000-4000-8000-000000000002';
const thirdId = '00000000-0000-4000-8000-000000000003';
const occurredAt = '2026-08-13T00:00:00.000Z';
const requestHash = 'a'.repeat(64);
const remoteLeaseToken = 'l'.repeat(43);
const remoteRunCredential = 'r'.repeat(43);

const remoteConversationLease = {
  epoch: 1,
  lease_token: remoteLeaseToken,
  run_credential: remoteRunCredential,
  runner_instance_id: thirdId,
};

const remoteConversationRunWorkData = {
  type: 'conversation_run',
  run_id: firstId,
  epoch: 1,
  lease_token: remoteLeaseToken,
  run_credential: remoteRunCredential,
  conversation_id: secondId,
  participant_id: thirdId,
  waker_ref: { kind: 'employee', id: firstId },
  waker_snapshot: {
    name: 'Remote Waker',
    role_name: 'Evidence reviewer',
    bio: 'Reviews bounded remote Work evidence.',
    system_prompt: 'Review the supplied evidence without using tools.',
  },
  employee_id: firstId,
  config_revision: 'configuration-1',
  trigger_message_ids: [secondId],
  previous_executor_session_id: 'session-1',
  resolved_model: 'gateway-test-model',
};

const remoteConversationRunWork = {
  id: thirdId,
  type: 'conversation_run',
  state: 'claimed',
  secret: remoteLeaseToken,
  token: remoteRunCredential,
  data: remoteConversationRunWorkData,
  created_at: occurredAt,
};

const principal = {
  userId: firstId,
  workspaceId: secondId,
  displayName: 'Operator',
  role: 'owner',
  permissions: ['wakers:write'],
};

const createWaker = {
  name: 'Backend',
  roleName: 'Backend Engineer',
  bio: 'Builds durable services.',
  environment: 'cloud',
};

const effectiveSnapshot = {
  profile: {
    name: 'Backend',
    roleName: 'Backend Engineer',
    bio: 'Builds durable services.',
    roleTemplateVersionId: null,
    avatarObjectId: null,
  },
  documents: { identity: firstId, persona: secondId, bible: thirdId, memory: firstId },
  resources: {
    skillInstallationVersionIds: [],
    knowledgeBindingVersionIds: [],
    connectorToolSelectionVersionIds: [],
    imPairingVersionIds: [],
    permissionPolicyVersionIds: [],
  },
  modelPolicy: {},
};

const documentVersion = {
  id: firstId,
  documentId: secondId,
  wakerId: thirdId,
  kind: 'identity',
  number: 1,
  content: '# Identity',
  sha256: requestHash,
  changeSummary: 'Initialized',
  restoredFromVersionId: null,
  createdBy: firstId,
  createdAt: occurredAt,
  isCurrent: true,
};

const skillVersion = {
  id: firstId,
  skillId: secondId,
  wakerId: thirdId,
  number: 1,
  name: 'Evidence Review',
  description: 'Reviews real release evidence.',
  source: 'markdown',
  state: 'installed',
  contentSha256: requestHash,
  markdown: '# Evidence Review\nCheck every claim.\n',
  fileName: 'SKILL.md',
  selfEvolution: false,
  historyKind: 'system',
  comparedWithVersionId: null,
  changeSummary: 'Initial installation',
  createdBy: firstId,
  createdAt: occurredAt,
  isCurrent: true,
};

const membershipVersion = {
  id: thirdId,
  groupId: firstId,
  number: 1,
  leaderWakerId: firstId,
  memberWakerIds: [firstId, secondId],
  memberConfigurations: [firstId, secondId].map((wakerId) => ({
    wakerId,
    model: 'gateway-test-model',
    workspaceReferenceId: null,
    configurationState: 'ready',
  })),
  reason: 'Initial membership',
  createdBy: thirdId,
  createdAt: occurredAt,
};

const event = {
  id: firstId,
  sequence: 1,
  type: 'run.created',
  occurredAt,
  payload: { executionTarget: 'cloud' },
};

const run = {
  id: firstId,
  taskId: secondId,
  attempt: 1,
  executionTarget: 'cloud',
  provider: 'deepseek',
  model: 'deepseek-chat',
  providerCorrelationId: null,
  status: 'queued',
  usage: null,
  failureCategory: null,
};

const roleRunReport = {
  schemaVersion: '3.0.0',
  reportType: 'role_run_completion',
  roleRunId: firstId,
  taskId: secondId,
  planVersion: 1,
  status: 'completed',
  summary: 'Implemented and verified the task.',
  inputSummary: 'Implement the confirmed Plan task.',
  roleResult: 'The task is ready for Leader review.',
  workPerformed: ['Implemented the requested behavior.'],
  changeSet: ['index.html'],
  artifacts: [{ path: 'index.html', displayName: 'Game', mediaType: 'text/html' }],
  evidence: [
    {
      requirementKey: 'source',
      acceptanceKeys: ['runs'],
      kind: 'artifact',
      artifactPath: 'index.html',
      summary: 'The source artifact is present.',
    },
  ],
  unresolvedIssues: [],
  nextStepInput: 'Leader can aggregate the result.',
  completion: {
    acceptanceKeys: ['runs'],
    evidenceRequirementKeys: ['source'],
    readyForReview: true,
  },
};

const groupPlanProposal = {
  schemaVersion: '3.0.0',
  reportType: 'group_plan_proposal',
  missionId: firstId,
  goal: 'Ship the feature.',
  scope: ['Implementation'],
  outOfScope: [],
  constraints: ['Use the shared workspace.'],
  tasks: [
    {
      taskKey: 'implementation',
      title: 'Implement feature',
      description: 'Implement and verify the feature.',
      ownerWakerId: secondId,
      reviewerWakerIds: [firstId],
      dependsOnTaskKeys: [],
      acceptanceCriteria: [{ key: 'runs', description: 'The feature runs.' }],
      evidenceRequirements: [{ key: 'source', kind: 'artifact', description: 'Submit the source artifact.' }],
      recommendedSkillIds: [],
    },
  ],
  risks: [],
  completionPolicy: 'All required evidence must be submitted.',
};

const workflowNodes = [
  { id: 'start', name: '准备', type: 'phase', next: ['implement'] },
  {
    id: 'implement',
    name: '实现',
    type: 'worker',
    next: ['approval'],
    wakerId: secondId,
    instruction: '实现 {{args.request}}。',
  },
  {
    id: 'approval',
    name: '确认',
    type: 'ask_user',
    next: ['done'],
    question: '是否交付？',
    responseKey: 'approved',
    choices: ['是', '否'],
    timeoutSeconds: null,
  },
  { id: 'done', name: '返回', type: 'return', next: [], value: { result: '{{results.implement}}' } },
];

const workflowDefinition = {
  name: '交付流程',
  description: '实现、确认并返回结果。',
  script: JSON.stringify({ startNodeId: 'start', nodes: workflowNodes }),
  startNodeId: 'start',
  inputSchema: [
    {
      key: 'request',
      label: '需求',
      description: '本次需要处理的需求。',
      type: 'string',
      required: true,
    },
  ],
  nodes: workflowNodes,
};

const workflowVersion = {
  id: thirdId,
  workflowId: firstId,
  number: 1,
  state: 'published',
  description: workflowDefinition.description,
  script: workflowDefinition.script,
  startNodeId: workflowDefinition.startNodeId,
  inputSchema: workflowDefinition.inputSchema,
  nodes: workflowDefinition.nodes,
  createdBy: secondId,
  createdAt: occurredAt,
};

interface SchemaFixture {
  valid: unknown;
  invalid: unknown;
}

const workflowAutomationDefinition = {
  name: 'Independent workflow task',
  enabled: true,
  triggers: [{ id: 'api', type: 'api' }],
  defaultArgs: {},
  timezone: 'Asia/Shanghai',
  missedRunPolicy: 'skip',
  maxRunCount: null,
  deadlineAt: null,
};

const fixtures: Record<string, SchemaFixture> = {
  V3WorkflowAutomationDispatchInputSchema: {
    valid: { triggerType: 'manual', deliveryIdentity: 'manual-debug', payload: {} },
    invalid: { triggerType: 'api', deliveryIdentity: 'missing-trigger' },
  },
  V3CreateWorkflowAutomationSchema: {
    valid: workflowAutomationDefinition,
    invalid: { ...workflowAutomationDefinition, triggers: [] },
  },
  V3DeleteWorkflowAutomationSchema: {
    valid: { expectedVersion: 1 },
    invalid: { expectedVersion: 0 },
  },
  V3UpdateWorkflowAutomationSchema: {
    valid: { ...workflowAutomationDefinition, expectedVersion: 1 },
    invalid: { ...workflowAutomationDefinition, expectedVersion: 1, workflowId: firstId },
  },
  V3WorkflowAutomationSchema: {
    valid: {
      id: firstId,
      workflowId: secondId,
      createdBy: thirdId,
      version: 1,
      configuration: workflowAutomationDefinition,
      automaticRunCount: 0,
      lastAutomaticRunAt: null,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      workflowId: secondId,
      version: 0,
      configuration: workflowAutomationDefinition,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
  },
  V3ArtifactKindSchema: { valid: 'artifact', invalid: 'run_output' },
  V3ArtifactTypeSchema: { valid: 'document', invalid: 'unknown' },
  V3ConversationArtifactManifestSchema: {
    valid: {
      conversationId: firstId,
      workingDirectory: null,
      workingDirectoryUrl: null,
      artifacts: [],
      fileChanges: [],
      fileUrls: {},
    },
    invalid: { conversationId: 'invalid' },
  },
  V3UiLanguageSchema: { valid: 'zh-CN', invalid: 'zh' },
  V3LanguageSettingSchema: {
    valid: { language: 'en-US', source: 'user', retryable: false, retryAfterMs: 0 },
    invalid: { language: 'fr-FR', source: 'user', retryable: false, retryAfterMs: 0 },
  },
  V3LanguageSettingInputSchema: { valid: { language: 'zh-CN' }, invalid: { language: 'zh' } },
  V3GroupSkillSchema: {
    valid: {
      id: firstId,
      groupId: secondId,
      versionId: thirdId,
      name: 'ui-designer',
      description: '',
      markdown: '# Skill',
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      groupId: secondId,
      versionId: thirdId,
      name: '',
      description: '',
      markdown: '# Skill',
      updatedAt: occurredAt,
    },
  },
  V3InstallGroupSkillsSchema: {
    valid: { preparedSkillIds: [firstId], expectedVersion: 1 },
    invalid: { preparedSkillIds: [], expectedVersion: 1 },
  },
  V3RemoveGroupSkillSchema: {
    valid: { skillId: firstId, expectedVersion: 1 },
    invalid: { skillId: firstId, expectedVersion: 0 },
  },
  V3PrincipalSchema: { valid: principal, invalid: { ...principal, workspaceId: 'another-workspace' } },
  V3PaginationInputSchema: { valid: { cursor: 'next', limit: 50 }, invalid: { limit: 0 } },
  V3PageSchema: {
    valid: { items: [{ id: firstId }], nextCursor: null, hasMore: false },
    invalid: { items: [], hasMore: 'no' },
  },
  V3ProblemSchema: {
    valid: {
      type: 'https://workdude.invalid/problems/conflict',
      title: 'Conflict',
      status: 409,
      correlationId: 'correlation-1',
      retryable: false,
    },
    invalid: { title: 'Conflict', status: 200, correlationId: 'correlation-1' },
  },
  V3IdempotencySchema: {
    valid: { key: 'message-create-0001', requestHash },
    invalid: { key: 'short', requestHash },
  },
  V3ExpectedVersionSchema: { valid: { expectedVersion: 1 }, invalid: { expectedVersion: 0 } },
  V3PermissionPolicyKindSchema: { valid: 'tool_guard', invalid: 'tool' },
  V3ToolDecisionSchema: { valid: 'ask', invalid: 'prompt' },
  V3PermissionPolicyConfigurationSchema: {
    valid: {
      kind: 'tool_guard',
      enabled: true,
      enabledRuleIds: ['TOOL_CMD_DANGEROUS_RM'],
      enabledShellEscapeRuleIds: ['SHELL_COMMAND_SUBSTITUTION'],
    },
    invalid: { kind: 'tool_guard', enabled: true },
  },
  V3PermissionPolicyVersionSchema: {
    valid: {
      id: firstId,
      policyId: secondId,
      wakerId: thirdId,
      kind: 'tool_guard',
      number: 1,
      configuration: {
        kind: 'tool_guard',
        enabled: true,
        enabledRuleIds: ['TOOL_CMD_DANGEROUS_RM'],
        enabledShellEscapeRuleIds: ['SHELL_COMMAND_SUBSTITUTION'],
      },
      createdBy: null,
      createdAt: occurredAt,
      isCurrent: true,
    },
    invalid: {
      id: firstId,
      policyId: secondId,
      wakerId: thirdId,
      kind: 'tool_guard',
      number: 0,
      configuration: {},
      createdBy: null,
      createdAt: occurredAt,
      isCurrent: true,
    },
  },
  V3UpdatePermissionPolicySchema: {
    valid: {
      expectedConfigurationVersionId: firstId,
      expectedPolicyVersionId: secondId,
      configuration: {
        kind: 'builtin_tools',
        enabled: true,
        decisions: { Bash: 'ask' },
      },
      changeSummary: 'Require Bash confirmation',
    },
    invalid: {
      expectedConfigurationVersionId: firstId,
      expectedPolicyVersionId: secondId,
      configuration: { kind: 'builtin_tools', enabled: true, decisions: { Bash: 'prompt' } },
      changeSummary: '',
    },
  },
  V3PolicyDecisionEvidenceSchema: {
    valid: {
      id: firstId,
      runId: secondId,
      requestHash,
      decision: 'ask',
      ruleIds: ['builtin.Bash'],
      policyVersionIds: [thirdId],
      normalizedTarget: '/workspace',
      reason: 'explicit user approval is required',
      occurredAt,
    },
    invalid: {
      id: firstId,
      runId: secondId,
      requestHash: 'invalid',
      decision: 'ask',
      ruleIds: [],
      policyVersionIds: [],
      normalizedTarget: '/workspace',
      reason: '',
      occurredAt,
    },
  },
  V3VersionMetadataSchema: {
    valid: { version: 1, createdAt: occurredAt, updatedAt: occurredAt },
    invalid: { version: 0, createdAt: occurredAt, updatedAt: occurredAt },
  },
  V3AvatarObjectSchema: {
    valid: {
      id: firstId,
      mediaType: 'image/png',
      sizeBytes: 12,
      sha256: requestHash,
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      mediaType: 'image/svg+xml',
      sizeBytes: 12,
      sha256: requestHash,
      createdAt: occurredAt,
    },
  },
  V3CreateWakerSchema: { valid: createWaker, invalid: { ...createWaker, name: '' } },
  V3WakerResourceSelectionSchema: {
    valid: {
      roleSkillNames: ['architecture'],
      knowledgeBaseIds: [firstId],
      mcpConfigs: [],
      skillPackagePreparationIds: [secondId],
    },
    invalid: { skillPackagePreparationIds: [firstId, firstId] },
  },
  V3UpdateWakerSchema: {
    valid: { ...createWaker, expectedVersion: 1 },
    invalid: { ...createWaker, expectedVersion: 0 },
  },
  V3WakerLifecycleInputSchema: {
    valid: { action: 'disable', expectedVersion: 1 },
    invalid: { action: 'delete', expectedVersion: 1 },
  },
  V3DefaultQuestionsSchema: {
    valid: { EN: ['Review this API'], ZH: ['审查这个接口'] },
    invalid: { EN: ['', 'Two', 'Three', 'Four'], ZH: [] },
  },
  V3GenerateRoleDocumentsInputSchema: {
    valid: { name: 'Role author', description: 'Creates evidence-based plans.' },
    invalid: { name: 'Role author', description: ' \n\t ' },
  },
  V3RoleDocumentsSchema: {
    valid: { identityMd: '# Identity', personaMd: '# Persona', bibleMd: '# Bible' },
    invalid: { identityMd: '', personaMd: '# Persona', bibleMd: '# Bible' },
  },
  V3CreateRoleTemplateSchema: {
    valid: {
      name: 'Backend role',
      summary: 'Backend delivery',
      identity: '',
      persona: '',
      bible: '',
      defaultQuestions: { EN: ['Review this API'], ZH: ['审查这个接口'] },
    },
    invalid: {
      name: 'A role template name that is too long',
      summary: 'Backend delivery',
      identity: '',
      persona: '',
      bible: '',
    },
  },
  V3RoleTemplateVersionSchema: {
    valid: {
      id: firstId,
      number: 1,
      identity: '',
      persona: '',
      bible: '',
      coreCapabilities: '[]',
      workStyles: '[]',
      deliveryCommitments: '[]',
      defaultQuestions: { EN: ['Review this API'], ZH: ['审查这个接口'] },
      createdBy: secondId,
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      number: 0,
      identity: 'You are a backend engineer.',
      persona: 'Precise and reliable.',
      bible: 'Ship tested APIs.',
      coreCapabilities: '[]',
      workStyles: '[]',
      deliveryCommitments: '[]',
      createdBy: secondId,
      createdAt: occurredAt,
    },
  },
  V3UpdateRoleTemplateSchema: {
    valid: {
      name: 'Backend role',
      summary: 'Backend delivery',
      identity: 'Identity',
      persona: 'Persona',
      bible: 'Bible',
      expectedVersionId: firstId,
      roleSkillVersionIds: [],
    },
    invalid: {
      name: 'Backend role',
      summary: 'Backend delivery',
      identity: 'Identity',
      persona: 'Persona',
      bible: 'Bible',
      expectedVersionId: 'bad',
      roleSkillVersionIds: [],
    },
  },
  V3RoleSkillVersionSchema: {
    valid: {
      resourceId: firstId,
      versionId: secondId,
      name: 'Evidence Review',
      description: 'Reviews evidence',
      source: 'upload',
      fileName: 'SKILL.md',
      mediaType: 'text/markdown',
      sizeBytes: 20,
      packageSha256: requestHash,
      contentSha256: requestHash,
      selfEvolution: false,
    },
    invalid: {
      resourceId: firstId,
      versionId: secondId,
      name: '',
      description: '',
      source: 'bad',
      fileName: '',
      mediaType: 'bad',
      sizeBytes: 0,
      packageSha256: 'bad',
      contentSha256: 'bad',
      selfEvolution: false,
    },
  },
  V3RoleTemplateSchema: {
    valid: {
      id: firstId,
      name: 'Backend role',
      summary: 'Backend delivery',
      source: 'custom',
      status: 'active',
      currentVersion: {
        id: secondId,
        number: 1,
        identity: 'You are a backend engineer.',
        persona: 'Precise and reliable.',
        bible: 'Ship tested APIs.',
        coreCapabilities: '[]',
        workStyles: '[]',
        deliveryCommitments: '[]',
        defaultQuestions: { EN: ['Review this API'], ZH: [] },
        createdBy: thirdId,
        createdAt: occurredAt,
      },
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      name: 'Backend role',
      summary: 'Backend delivery',
      source: 'fixture',
      status: 'active',
    },
  },
  V3WakerSchema: {
    valid: {
      id: firstId,
      ...createWaker,
      status: 'online',
      version: 1,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, ...createWaker, status: 'pretending', version: 1 },
  },
  V3WakerShareConfigSchema: {
    valid: { expirationPreset: '7d', usagePreset: 'once' },
    invalid: { expirationPreset: '90d', usagePreset: 'once' },
  },
  V3WakerShareIncludeOptionsSchema: {
    valid: {
      profile: true,
      about: true,
      skills: true,
      connectors: false,
      automations: true,
      memory: false,
      projects: false,
      permissions: false,
    },
    invalid: {
      profile: true,
      about: true,
      skills: true,
      connectors: false,
      automations: true,
      memory: false,
      projects: false,
      permissions: false,
      providerApiKey: 'must-not-cross-share-contract',
    },
  },
  V3WakerShareCreateSchema: {
    valid: {
      includeOptions: {
        profile: true,
        about: true,
        skills: true,
        connectors: false,
        automations: true,
        memory: false,
        projects: false,
        permissions: false,
      },
      shareConfig: { expirationPreset: '3d', usagePreset: 'unlimited' },
    },
    invalid: { includeOptions: { profile: true } },
  },
  V3WakerShareCreatedSchema: {
    valid: { shareId: 'share_01ABC', packageSize: 69908 },
    invalid: { shareId: '', packageSize: -1 },
  },
  V3WakerShareLinkRowSchema: {
    valid: {
      share_id: 'share_01ABC',
      status: 'active',
      created_at: occurredAt,
      share_count: 1,
      extension_name: 'Backend Waker',
      description: 'A shared Waker package.',
      author: 'Operator',
      extension_version: '1.0.0',
      local_avatar: 'https://example.test/avatar.png',
      expires_at: '2026-08-20T00:00:00.000Z',
      failure_reason: undefined,
    },
    invalid: {
      share_id: 'share_01ABC',
      status: 'active',
      created_at: occurredAt,
      createdBy: 'operator-secret',
    },
  },
  V3WakerShareLinkListSchema: {
    valid: { share_links: [] },
    invalid: { share_links: [{ share_id: 'share_01ABC' }] },
  },
  V3WakerShareLinkListQuerySchema: {
    valid: { page: 1, pageSize: 20, status: 'active' },
    invalid: { page: 0, pageSize: 101 },
  },
  V3WakerImportLinkSchema: {
    valid: { url: 'https://qoderwake.example/share/share_01ABC', name: 'Imported Backend' },
    invalid: { url: '', name: '' },
  },
  V3WakerDocumentKindSchema: { valid: 'identity', invalid: 'profile' },
  V3WakerDocumentVersionSchema: {
    valid: documentVersion,
    invalid: { ...documentVersion, number: 0 },
  },
  V3WakerEffectiveSnapshotSchema: {
    valid: effectiveSnapshot,
    invalid: { ...effectiveSnapshot, documents: { identity: firstId } },
  },
  V3WakerConfigurationVersionSchema: {
    valid: {
      id: firstId,
      wakerId: secondId,
      number: 1,
      effectiveSnapshot,
      snapshotSha256: requestHash,
      createdBy: thirdId,
      reason: 'Created',
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      wakerId: secondId,
      number: 0,
      effectiveSnapshot,
      snapshotSha256: requestHash,
      createdBy: thirdId,
      reason: 'Created',
      createdAt: occurredAt,
    },
  },
  V3UpdateWakerDocumentSchema: {
    valid: {
      expectedConfigurationVersionId: firstId,
      content: '# Updated',
      changeSummary: 'Update identity',
    },
    invalid: { expectedConfigurationVersionId: firstId, content: '# Updated', changeSummary: '' },
  },
  V3RestoreWakerDocumentSchema: {
    valid: { expectedConfigurationVersionId: firstId, versionId: secondId },
    invalid: { expectedConfigurationVersionId: 'invalid', versionId: secondId },
  },
  V3DocumentComparisonSchema: {
    valid: {
      kind: 'identity',
      from: documentVersion,
      to: { ...documentVersion, id: secondId, number: 2, isCurrent: true },
      addedLines: 1,
      removedLines: 0,
      unchangedLines: 1,
    },
    invalid: {
      kind: 'identity',
      from: documentVersion,
      to: documentVersion,
      addedLines: -1,
      removedLines: 0,
      unchangedLines: 1,
    },
  },
  V3MemoryTimelineEventKindSchema: { valid: 'memory_added', invalid: 'memory_forgotten' },
  V3MemoryTimelineOriginSchema: { valid: 'manual_update', invalid: 'automatic_update' },
  V3MemoryTimelineEventSchema: {
    valid: {
      id: firstId,
      wakerId: secondId,
      scope: 'waker',
      projectId: null,
      kind: 'memory_added',
      title: '在个人记忆的后端工程师部分沉淀了健康检查要点',
      description: '新增了健康检查、告警和回滚要点。',
      origin: 'manual_update',
      documentVersionId: thirdId,
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      wakerId: secondId,
      scope: 'global',
      projectId: null,
      kind: 'memory_added',
      title: '在个人记忆的后端工程师部分沉淀了健康检查要点',
      description: '新增了健康检查、告警和回滚要点。',
      origin: 'unknown',
      documentVersionId: thirdId,
      createdAt: occurredAt,
    },
  },
  V3MemoryTimelineQuerySchema: {
    valid: { scope: 'waker', limit: 50 },
    invalid: { scope: 'waker', limit: 0 },
  },
  V3CreateGroupSchema: {
    valid: {
      name: 'Delivery',
      mission: 'Ship V3',
      leaderWakerId: firstId,
      memberWakerIds: [firstId],
      memberConfigurations: [
        {
          wakerId: firstId,
          model: 'gateway-test-model',
          workspaceReferenceId: null,
        },
      ],
    },
    invalid: { name: 'Delivery', leaderWakerId: firstId, memberWakerIds: [] },
  },
  V3RenameGroupSchema: {
    valid: { name: 'Delivery 2', expectedVersion: 1 },
    invalid: { name: '', expectedVersion: 1 },
  },
  V3GroupLifecycleInputSchema: {
    valid: { action: 'archive', expectedVersion: 1 },
    invalid: { action: 'delete', expectedVersion: 1 },
  },
  V3GroupMemberConfigurationInputSchema: {
    valid: { wakerId: firstId, model: 'gateway-test-model', workspaceReferenceId: null },
    invalid: { wakerId: firstId, model: '', workspaceReferenceId: null },
  },
  V3GroupMemberConfigurationSchema: {
    valid: {
      wakerId: firstId,
      model: 'gateway-test-model',
      workspaceReferenceId: null,
      configurationState: 'ready',
    },
    invalid: {
      wakerId: firstId,
      model: null,
      workspaceReferenceId: null,
      configurationState: 'unknown',
    },
  },
  V3GroupMembershipVersionSchema: {
    valid: membershipVersion,
    invalid: { ...membershipVersion, number: 0 },
  },
  V3GroupSchema: {
    valid: {
      id: firstId,
      name: 'Delivery',
      mission: 'Ship V3',
      status: 'active',
      currentMembershipVersion: membershipVersion,
      version: 1,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, name: 'Delivery', status: 'active' },
  },
  V3CreateConversationSchema: {
    valid: { subjectType: 'waker', subjectId: firstId, title: 'V3 proof' },
    invalid: { subjectType: 'device', subjectId: firstId, title: 'V3 proof' },
  },
  V3ConversationSchema: {
    valid: {
      id: firstId,
      subjectType: 'waker',
      subjectId: secondId,
      title: 'V3 proof',
      workspaceReferenceId: null,
      projectId: null,
      status: 'active',
      lastEventSequence: 0,
      version: 1,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, subjectType: 'waker', subjectId: secondId, title: '' },
  },
  V3ConversationAttachmentSchema: {
    valid: {
      id: firstId,
      fileName: 'brief.bin',
      mediaType: 'application/octet-stream',
      sizeBytes: 12,
      sha256: requestHash,
    },
    invalid: {
      id: firstId,
      fileName: '',
      mediaType: 'application/octet-stream',
      sizeBytes: 0,
      sha256: 'invalid',
    },
  },
  V3SendMessageSchema: {
    valid: { content: '', attachmentIds: [firstId], responseLanguage: 'zh-CN' },
    invalid: { content: 'x'.repeat(100_001) },
  },
  V3ConfirmGroupPlanSchema: {
    valid: { planVersion: 2 },
    invalid: { planVersion: 0 },
  },
  V3GroupAcceptanceCriterionSchema: {
    valid: { key: 'runs', description: 'The game runs.' },
    invalid: { key: 'runs', description: '' },
  },
  V3GroupEvidenceKindSchema: {
    valid: 'verification_report',
    invalid: 'claim',
  },
  V3GroupEvidenceRequirementSchema: {
    valid: { key: 'runtime', kind: 'verification_report', description: 'HTTP returns 200.' },
    invalid: { key: 'runtime', kind: 'claim', description: 'HTTP returns 200.' },
  },
  V3RoleRunArtifactReferenceSchema: {
    valid: { path: 'index.html', displayName: 'Game', mediaType: 'text/html' },
    invalid: { path: '', displayName: 'Game', mediaType: 'text/html' },
  },
  V3RoleRunEvidenceSubmissionSchema: {
    valid: roleRunReport.evidence[0],
    invalid: { ...roleRunReport.evidence[0], acceptanceKeys: [] },
  },
  V3RoleRunReportSchema: {
    valid: roleRunReport,
    invalid: { ...roleRunReport, schemaVersion: '2.0.0' },
  },
  V3GroupPlanProposalSchema: {
    valid: groupPlanProposal,
    invalid: { ...groupPlanProposal, tasks: [] },
  },
  V3TaskSchema: {
    valid: {
      id: firstId,
      parentTaskId: null,
      sourceType: 'conversation',
      sourceId: secondId,
      type: 'individual',
      title: 'Inspect workspace',
      state: 'queued',
      actionNeeded: null,
      sourceUrl: '/conversations/00000000-0000-4000-8000-000000000002',
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, state: 'done' },
  },
  V3TaskStateCountsSchema: {
    valid: {
      draft: 0,
      awaiting_confirmation: 0,
      queued: 1,
      preparing: 0,
      running: 0,
      awaiting_approval: 0,
      awaiting_input: 0,
      completed: 0,
      failed: 0,
      cancelled: 0,
    },
    invalid: { queued: -1 },
  },
  V3TaskPageSchema: {
    valid: {
      items: [
        {
          id: firstId,
          parentTaskId: null,
          sourceType: 'conversation',
          sourceId: secondId,
          type: 'individual',
          title: 'Inspect workspace',
          state: 'queued',
          actionNeeded: null,
          sourceUrl: '/conversations/00000000-0000-4000-8000-000000000002',
          updatedAt: occurredAt,
        },
      ],
      nextCursor: null,
      hasMore: false,
      total: 1,
      counts: {
        draft: 0,
        awaiting_confirmation: 0,
        queued: 1,
        preparing: 0,
        running: 0,
        awaiting_approval: 0,
        awaiting_input: 0,
        completed: 0,
        failed: 0,
        cancelled: 0,
      },
    },
    invalid: { items: [], nextCursor: null, hasMore: false, total: -1, counts: {} },
  },
  V3ModelUsageSchema: {
    valid: { inputTokens: 10, outputTokens: 5, totalTokens: 15 },
    invalid: { inputTokens: -1, outputTokens: 5, totalTokens: 4 },
  },
  V3RunSchema: { valid: run, invalid: { ...run, provider: 'invalid provider URL' } },
  V3ConversationRunPageSchema: {
    valid: { runs: [{ run, wakerId: firstId, sessionId: null }], hasMore: false, nextCursor: '' },
    invalid: { runs: [{ run, wakerId: firstId, sessionId: 1 }], hasMore: false, nextCursor: '' },
  },
  V3GroupActivitySnapshotSchema: {
    valid: {
      events: [{ ...event, workspaceId: secondId, runId: thirdId, correlationId: 'correlation-1' }],
      runCursors: [{ runId: thirdId, afterSequence: 0 }],
    },
    invalid: { events: [], runCursors: [{ runId: thirdId, afterSequence: -1 }] },
  },
  V3EventSchema: { valid: event, invalid: { ...event, sequence: 0 } },
  V3DurableEventSchema: {
    valid: {
      ...event,
      workspaceId: secondId,
      runId: thirdId,
      correlationId: 'correlation-1',
    },
    invalid: { ...event, workspaceId: secondId, runId: thirdId },
  },
  V3EventPageSchema: {
    valid: { events: [event], afterSequence: 0, nextAfterSequence: 1, hasMore: false },
    invalid: { events: [event], afterSequence: -1, nextAfterSequence: 1, hasMore: false },
  },
  V3ApprovalSchema: {
    valid: {
      id: firstId,
      runId: secondId,
      capability: 'sandbox.exec',
      requestHash,
      scope: 'workspace-reference:proof',
      risk: 'execute',
      status: 'pending',
      policyVersion: 1,
      requestedAt: occurredAt,
      expiresAt: occurredAt,
    },
    invalid: { id: firstId, runId: secondId, requestHash: 'not-a-hash' },
  },
  V3ApprovalWorkItemSchema: {
    valid: {
      approval: {
        id: firstId,
        runId: secondId,
        capability: 'sandbox.exec',
        requestHash,
        scope: 'workspace-reference:proof',
        risk: 'execute',
        status: 'pending',
        policyVersion: 1,
        requestedAt: occurredAt,
        expiresAt: occurredAt,
      },
      task: {
        id: thirdId,
        parentTaskId: null,
        sourceType: 'conversation',
        sourceId: secondId,
        type: 'individual',
        title: 'Approve workspace command',
        state: 'awaiting_approval',
        actionNeeded: 'tool_approval',
        sourceUrl: '/conversations/00000000-0000-4000-8000-000000000002',
        updatedAt: occurredAt,
      },
    },
    invalid: { approval: {}, task: {} },
  },
  V3ResolveApprovalSchema: {
    valid: { decision: 'approved', requestHash },
    invalid: { decision: 'approved', requestHash: 'not-a-hash' },
  },
  V3ArtifactSchema: {
    valid: {
      id: firstId,
      runId: secondId,
      fileObjectId: thirdId,
      kind: 'artifact',
      artifactType: 'document',
      source: 'present_files',
      toolName: null,
      title: 'Proof',
      description: null,
      relativePath: 'proof.txt',
      displayName: 'proof.txt',
      mediaType: 'text/plain',
      sizeBytes: 5,
      sha256: requestHash,
      state: 'available',
      createdAt: occurredAt,
    },
    invalid: { id: firstId, runId: secondId, sizeBytes: -1, sha256: requestHash },
  },
  V3WorkspaceReferenceSchema: {
    valid: {
      id: firstId,
      kind: 'local_directory',
      displayName: 'workspace',
      availability: 'available',
      version: 1,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      kind: 'raw_path',
      displayName: 'workspace',
      availability: 'available',
      version: 1,
    },
  },
  V3ProjectVisibilitySchema: { valid: 'workspace', invalid: 'public' },
  V3ProjectSourceInputSchema: {
    valid: { kind: 'git_repository', locator: 'https://github.com/example/project.git', branch: 'main' },
    invalid: { kind: 'git_repository', locator: 'git@github.com:example/project.git', branch: 'main' },
  },
  V3ProjectSourceSchema: {
    valid: {
      id: thirdId,
      kind: 'git_repository',
      workspaceReferenceId: null,
      locator: 'https://github.com/example/project.git',
      branch: 'main',
      displayName: 'project.git',
      availability: 'available',
      position: 0,
    },
    invalid: {
      id: thirdId,
      kind: 'git_repository',
      workspaceReferenceId: null,
      locator: null,
      branch: null,
      displayName: '',
      availability: 'available',
      position: -1,
    },
  },
  V3CreateProjectSchema: {
    valid: {
      name: 'Minesweeper',
      summary: 'A browser game.',
      visibility: 'workspace',
      sources: [
        { kind: 'git_repository', locator: 'https://github.com/example/project.git', branch: 'main' },
      ],
    },
    invalid: { name: '', summary: '', visibility: 'workspace', sources: [] },
  },
  V3UpdateProjectSchema: {
    valid: {
      name: 'Minesweeper',
      summary: 'A browser game.',
      sources: [{ kind: 'local_directory', workspaceReferenceId: firstId }],
      expectedVersion: 2,
    },
    invalid: {
      name: 'Minesweeper',
      summary: 'A browser game.',
      visibility: 'workspace',
      sources: [{ kind: 'local_directory', workspaceReferenceId: firstId }],
      expectedVersion: 2,
    },
  },
  V3ProjectLifecycleInputSchema: {
    valid: { action: 'archive', expectedVersion: 1 },
    invalid: { action: 'delete', expectedVersion: 1 },
  },
  V3ProjectPreparationStateSchema: { valid: 'initializing', invalid: 'queued' },
  V3ProjectPreparationSchema: {
    valid: {
      state: 'error',
      attempt: 2,
      errorCode: 'git-clone-failed',
      errorDetail: 'Git repository could not be prepared.',
      updatedAt: occurredAt,
    },
    invalid: { state: 'error', attempt: 0, errorCode: null, errorDetail: null, updatedAt: occurredAt },
  },
  V3RetryProjectPreparationSchema: {
    valid: { expectedVersion: 2 },
    invalid: { expectedVersion: 0 },
  },
  V3ProjectSchema: {
    valid: {
      id: secondId,
      ownerWakerId: null,
      name: 'Minesweeper',
      summary: 'A browser game.',
      visibility: 'workspace',
      availability: 'available',
      preparation: {
        state: 'ready',
        attempt: 1,
        errorCode: null,
        errorDetail: null,
        updatedAt: occurredAt,
      },
      sources: [
        {
          id: thirdId,
          kind: 'git_repository',
          workspaceReferenceId: null,
          locator: 'https://github.com/example/project.git',
          branch: 'main',
          displayName: 'project.git',
          availability: 'available',
          position: 0,
        },
      ],
      version: 1,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: secondId, name: 'Minesweeper', visibility: 'public', sources: [] },
  },
  V3RegisterCloudWorkspaceSchema: {
    valid: { name: 'Cloud project', projectLocator: 'project/opaque-locator' },
    invalid: { name: '', projectLocator: 'project/opaque-locator' },
  },
  V3AutomationStatusSchema: { valid: 'enabled', invalid: 'running' },
  V3AutomationTriggerSchema: {
    valid: { id: 'daily', type: 'schedule', mode: 'recurring', cadence: 'daily', time: '09:00' },
    invalid: { id: 'daily', type: 'schedule', mode: 'recurring', cadence: 'daily', time: '25:00' },
  },
  V3RenameTaskSchema: {
    valid: { title: 'Renamed session', expectedUpdatedAt: occurredAt },
    invalid: { title: '', expectedUpdatedAt: 'not-a-date' },
  },
  V3HideTaskSchema: {
    valid: { expectedUpdatedAt: occurredAt },
    invalid: { expectedUpdatedAt: 'not-a-date' },
  },
  V3PinTaskSchema: {
    valid: { pinned: true, expectedUpdatedAt: occurredAt },
    invalid: { pinned: 'yes', expectedUpdatedAt: occurredAt },
  },
  V3AutomationRetryPolicySchema: {
    valid: { maxAttempts: 3, delaySeconds: 30 },
    invalid: { maxAttempts: 0, delaySeconds: 0 },
  },
  V3CreateAutomationSchema: {
    valid: {
      name: 'Daily audit',
      instruction: 'Audit {{repository}}.',
      workspaceReferenceId: null,
      model: 'deepseek-chat',
      triggers: [{ id: 'api', type: 'api' }],
      timezone: 'Asia/Shanghai',
      missedRunPolicy: 'run_once',
      overlapPolicy: 'queue',
      retryPolicy: { maxAttempts: 3, delaySeconds: 30 },
      maxRunCount: null,
      deadlineAt: null,
    },
    invalid: {
      name: '',
      instruction: '',
      model: 'deepseek-chat',
      triggers: [],
      timezone: '',
      missedRunPolicy: 'later',
      overlapPolicy: 'parallel',
      retryPolicy: { maxAttempts: 0, delaySeconds: 0 },
      maxRunCount: null,
      deadlineAt: null,
    },
  },
  V3UpdateAutomationSchema: {
    valid: {
      expectedVersion: 1,
      name: 'Daily audit',
      instruction: 'Audit {{repository}}.',
      workspaceReferenceId: null,
      model: 'deepseek-chat',
      triggers: [{ id: 'api', type: 'api' }],
      timezone: 'Asia/Shanghai',
      missedRunPolicy: 'run_once',
      overlapPolicy: 'queue',
      retryPolicy: { maxAttempts: 3, delaySeconds: 30 },
      maxRunCount: null,
      deadlineAt: null,
    },
    invalid: {
      expectedVersion: 0,
      name: 'Daily audit',
      instruction: 'Audit.',
      model: 'deepseek-chat',
      triggers: [{ id: 'api', type: 'api' }],
      timezone: 'Asia/Shanghai',
      missedRunPolicy: 'run_once',
      overlapPolicy: 'queue',
      retryPolicy: { maxAttempts: 3, delaySeconds: 30 },
      maxRunCount: null,
      deadlineAt: null,
    },
  },
  V3AutomationVersionSchema: {
    valid: {
      id: firstId,
      automationId: secondId,
      number: 1,
      instruction: 'Audit {{repository}}.',
      workspaceReferenceId: null,
      model: 'deepseek-chat',
      triggers: [{ id: 'api', type: 'api', invokeKey: 'a'.repeat(43) }],
      timezone: 'Asia/Shanghai',
      missedRunPolicy: 'run_once',
      overlapPolicy: 'queue',
      retryPolicy: { maxAttempts: 3, delaySeconds: 30 },
      maxRunCount: null,
      deadlineAt: null,
      createdBy: thirdId,
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      automationId: secondId,
      number: 0,
      instruction: '',
      model: '',
      triggers: [],
      timezone: '',
      missedRunPolicy: 'run_once',
      overlapPolicy: 'queue',
      retryPolicy: { maxAttempts: 0, delaySeconds: 0 },
      maxRunCount: null,
      deadlineAt: null,
      createdBy: thirdId,
      createdAt: occurredAt,
    },
  },
  V3AutomationSchema: {
    valid: {
      id: firstId,
      wakerId: secondId,
      name: 'Daily audit',
      status: 'enabled',
      version: 1,
      runCount: 0,
      currentVersion: {
        id: thirdId,
        automationId: firstId,
        number: 1,
        instruction: 'Audit {{repository}}.',
        workspaceReferenceId: null,
        model: 'deepseek-chat',
        triggers: [{ id: 'api', type: 'api', invokeKey: 'a'.repeat(43) }],
        timezone: 'Asia/Shanghai',
        missedRunPolicy: 'run_once',
        overlapPolicy: 'queue',
        retryPolicy: { maxAttempts: 3, delaySeconds: 30 },
        maxRunCount: null,
        deadlineAt: null,
        createdBy: secondId,
        createdAt: occurredAt,
      },
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, wakerId: secondId, name: '', status: 'enabled', version: 0 },
  },
  V3AutomationLifecycleInputSchema: {
    valid: { action: 'disable', expectedVersion: 1 },
    invalid: { action: 'pause', expectedVersion: 0 },
  },
  V3AutomationInvocationSchema: {
    valid: {
      id: firstId,
      deliveryId: secondId,
      automationId: thirdId,
      automationVersion: 1,
      summary: 'Audit the repository.',
      triggerType: 'api',
      deliveryIdentity: 'delivery-0001',
      conversationId: firstId,
      taskId: secondId,
      runId: thirdId,
      attempt: 1,
      state: 'queued',
      failure: null,
      scheduledAt: null,
      startedAt: null,
      finishedAt: null,
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      deliveryId: secondId,
      automationId: thirdId,
      automationVersion: 0,
      summary: '',
      triggerType: 'unknown',
      deliveryIdentity: '',
      conversationId: null,
      taskId: null,
      runId: null,
      attempt: 0,
      state: 'unknown',
      failure: null,
      scheduledAt: null,
      startedAt: null,
      finishedAt: null,
      createdAt: occurredAt,
    },
  },
  V3AutomationDispatchInputSchema: {
    valid: {
      triggerType: 'api',
      triggerId: 'api',
      deliveryIdentity: 'delivery-0001',
      payload: { repository: 'workdude' },
    },
    invalid: { triggerType: 'api', deliveryIdentity: '', payload: {} },
  },
  V3AutomationDispatchResultSchema: {
    valid: {
      created: true,
      invocation: {
        id: firstId,
        deliveryId: secondId,
        automationId: thirdId,
        automationVersion: 1,
        summary: 'Run the manual task.',
        triggerType: 'manual',
        deliveryIdentity: 'manual-0001',
        conversationId: null,
        taskId: null,
        runId: null,
        attempt: 1,
        state: 'skipped',
        failure: null,
        scheduledAt: null,
        startedAt: null,
        finishedAt: null,
        createdAt: occurredAt,
      },
      conversation: null,
      task: null,
      run: null,
    },
    invalid: { created: true, invocation: {}, conversation: null, task: null, run: null },
  },
  V3WorkflowInputFieldSchema: {
    valid: workflowDefinition.inputSchema[0],
    invalid: { key: 'not valid', label: '', description: '', type: 'text', required: true },
  },
  V3WorkflowNodeSchema: {
    valid: workflowNodes[1],
    invalid: { id: '1-invalid', name: '', type: 'worker', next: [], instruction: '' },
  },
  V3CreateWorkflowSchema: {
    valid: workflowDefinition,
    invalid: { ...workflowDefinition, name: '', nodes: [] },
  },
  V3UpdateWorkflowSchema: {
    valid: { expectedVersion: 1, ...workflowDefinition },
    invalid: { expectedVersion: 0, ...workflowDefinition },
  },
  V3WorkflowVersionSchema: {
    valid: workflowVersion,
    invalid: { ...workflowVersion, number: 0 },
  },
  V3WorkflowSchema: {
    valid: {
      automaticRunCount: 0,
      lastAutomaticRunAt: null,
      id: firstId,
      ownerWakerId: thirdId,
      conversationId: secondId,
      name: workflowDefinition.name,
      status: 'published',
      version: 2,
      currentVersion: workflowVersion,
      publishedVersion: workflowVersion,
      triggerConfiguration: {
        enabled: true,
        triggers: [{ id: 'api', type: 'api', invokeKey: 'workflow-secret-key-0000000000000000' }],
        defaultArgs: { repository: 'workdude' },
        timezone: 'Asia/Shanghai',
        missedRunPolicy: 'run_once',
        maxRunCount: 10,
        deadlineAt: null,
      },
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, name: '', status: 'running', version: 0 },
  },
  V3WorkflowTriggerConfigurationSchema: {
    valid: {
      enabled: true,
      triggers: [{ id: 'api', type: 'api', invokeKey: 'workflow-secret-key-0000000000000000' }],
      defaultArgs: { repository: 'workdude' },
      timezone: 'Asia/Shanghai',
      missedRunPolicy: 'run_once',
      maxRunCount: 10,
      deadlineAt: null,
    },
    invalid: {
      triggers: [],
      defaultArgs: {},
      timezone: '',
      missedRunPolicy: 'later',
      maxRunCount: 0,
      deadlineAt: null,
    },
  },
  V3UpdateWorkflowTriggersSchema: {
    valid: {
      expectedVersion: 2,
      triggers: [
        {
          id: 'event',
          type: 'event',
          provider: 'github',
          repository: 'bujidaoei/workdude',
          resources: ['pull_request'],
          changes: ['opened'],
        },
      ],
      defaultArgs: {},
      timezone: 'UTC',
      missedRunPolicy: 'skip',
      maxRunCount: null,
      deadlineAt: null,
    },
    invalid: {
      expectedVersion: 0,
      triggers: [],
      defaultArgs: {},
      timezone: '',
      missedRunPolicy: 'skip',
      maxRunCount: null,
      deadlineAt: null,
    },
  },
  V3WorkflowTriggerDispatchInputSchema: {
    valid: {
      triggerType: 'api',
      triggerId: 'api',
      deliveryIdentity: 'delivery-0001',
      payload: { repository: 'workdude' },
      scheduledAt: null,
    },
    invalid: { triggerType: 'manual', triggerId: '', deliveryIdentity: '' },
  },
  V3WorkflowLifecycleInputSchema: {
    valid: { action: 'publish', expectedVersion: 1 },
    invalid: { action: 'enable', expectedVersion: 0 },
  },
  V3WorkflowRollbackInputSchema: {
    valid: { expectedVersion: 2, versionNumber: 1 },
    invalid: { expectedVersion: 0, versionNumber: 0 },
  },
  V3WorkflowRunInputSchema: {
    valid: { triggerType: 'manual', deliveryIdentity: 'manual-0001', args: { request: '实现扫雷' } },
    invalid: { triggerType: 'manual', deliveryIdentity: '', args: {} },
  },
  V3WorkflowRunSchema: {
    valid: {
      id: secondId,
      workflowId: firstId,
      workflowVersion: 1,
      triggerType: 'manual',
      deliveryIdentity: 'manual-0001',
      state: 'awaiting_input',
      args: { request: '实现扫雷' },
      output: null,
      pendingNodeId: 'approval',
      failure: null,
      startedAt: occurredAt,
      finishedAt: null,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: secondId, workflowId: firstId, workflowVersion: 0, state: 'waiting' },
  },
  V3WorkflowRunEventSchema: {
    valid: {
      id: thirdId,
      workflowRunId: secondId,
      sequence: 1,
      type: 'input.requested',
      nodeId: 'approval',
      payload: { question: '是否交付？' },
      occurredAt,
    },
    invalid: { id: thirdId, workflowRunId: secondId, sequence: 0, type: 'unknown' },
  },
  V3WorkflowNodeExecutionSchema: {
    valid: {
      workflowRunId: secondId,
      nodeId: 'review',
      taskId: thirdId,
      assigneeWakerId: firstId,
      agentRunId: firstId,
      conversationId: secondId,
    },
    invalid: { workflowRunId: secondId, nodeId: '', taskId: thirdId },
  },
  V3ResolveWorkflowInputSchema: {
    valid: { nodeId: 'approval', response: '是' },
    invalid: { nodeId: '', response: '是' },
  },
  V3CreateKnowledgeBaseSchema: {
    valid: { name: 'Architecture Notes', description: 'Verified system design references.' },
    invalid: { name: '', description: 'Missing name.' },
  },
  V3KnowledgeCatalogSchema: {
    valid: 'featured',
    invalid: 'qmind',
  },
  V3KnowledgeListInputSchema: {
    valid: { catalog: 'shared', limit: 100 },
    invalid: { catalog: 'qmind' },
  },
  V3KnowledgeBaseSchema: {
    valid: {
      id: firstId,
      ownerUserId: secondId,
      name: 'Architecture Notes',
      description: 'Verified system design references.',
      status: 'ready',
      currentCompilationVersion: 1,
      sourceCount: 1,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      ownerUserId: secondId,
      name: 'Architecture Notes',
      description: '',
      status: 'pretending',
      currentCompilationVersion: 0,
      sourceCount: 0,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
  },
  V3KnowledgeEmailPreviewSchema: {
    valid: {
      subject: '通知',
      from: 'a@example.test',
      to: 'b@example.test',
      cc: '',
      sentAt: null,
      attachmentCount: 0,
      html: '',
      text: '正文',
    },
    invalid: {
      subject: '通知',
      from: 'a@example.test',
      to: 'b@example.test',
      cc: '',
      sentAt: null,
      attachmentCount: -1,
      html: '',
      text: '正文',
    },
  },
  V3KnowledgeFolderSchema: {
    valid: {
      id: firstId,
      knowledgeBaseId: secondId,
      parentFolderId: null,
      name: '产品资料',
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      knowledgeBaseId: secondId,
      parentFolderId: null,
      name: '   ',
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
  },
  V3CreateKnowledgeFolderSchema: {
    valid: { name: '产品资料', parentFolderId: null },
    invalid: { name: '   ', parentFolderId: null },
  },
  V3RenameKnowledgeMaterialSchema: {
    valid: { name: '已验证邮件' },
    invalid: { name: '   ' },
  },
  V3RenameKnowledgeFolderSchema: {
    valid: { name: '已验证资料' },
    invalid: { name: '   ' },
  },
  V3DeleteKnowledgeSelectionSchema: {
    valid: { folderIds: [firstId], materialIds: [] },
    invalid: { folderIds: [], materialIds: [] },
  },
  V3CreateKnowledgeUrlMaterialSchema: {
    valid: { title: 'QoderWake Docs', sourceUrl: 'https://example.com/qoderwake', parentFolderId: firstId },
    invalid: { title: 'QoderWake Docs', sourceUrl: 'not-a-url' },
  },
  V3KnowledgeMaterialSchema: {
    valid: {
      id: firstId,
      knowledgeBaseId: secondId,
      parentFolderId: null,
      kind: 'url',
      fileObjectId: null,
      sourceUrl: 'https://example.com/qoderwake',
      title: 'QoderWake Docs',
      sourceSha256: requestHash,
      processingState: 'ready',
      failureDetail: null,
      compiledVersion: 1,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      knowledgeBaseId: secondId,
      parentFolderId: null,
      kind: 'url',
      fileObjectId: null,
      sourceUrl: 'not-a-url',
      title: 'QoderWake Docs',
      sourceSha256: requestHash,
      processingState: 'ready',
      failureDetail: null,
      compiledVersion: 1,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
  },
  V3KnowledgeMaterialContentSchema: {
    valid: {
      materialId: firstId,
      fileName: 'reference.md',
      mediaType: 'text/markdown',
      sizeBytes: 128,
      compiledText: '# Verified content',
      compiledSha256: requestHash,
      characterCount: 18,
    },
    invalid: {
      materialId: 'invalid',
      fileName: 'reference.md',
      mediaType: 'text/markdown',
      sizeBytes: 128,
      compiledText: '# Verified content',
      compiledSha256: requestHash,
      characterCount: 18,
    },
  },
  V3KnowledgeCardSchema: {
    valid: {
      id: firstId,
      knowledgeBaseId: secondId,
      materialId: thirdId,
      position: 0,
      title: 'Verified architecture',
      contentMarkdown: '# Verified architecture\n\nEvidence-backed content.',
      keywords: ['architecture', 'evidence'],
      relatedCardIds: [],
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      knowledgeBaseId: secondId,
      materialId: thirdId,
      position: -1,
      title: 'Verified architecture',
      contentMarkdown: '# Verified architecture',
      keywords: [],
      relatedCardIds: [],
      createdAt: occurredAt,
    },
  },
  V3InviteKnowledgeCollaboratorSchema: {
    valid: { email: 'reviewer@example.com', role: 'viewer' },
    invalid: { email: 'invalid', role: 'owner' },
  },
  V3KnowledgeCollaboratorSchema: {
    valid: {
      id: firstId,
      knowledgeBaseId: secondId,
      userId: null,
      email: 'reviewer@example.com',
      displayName: null,
      role: 'viewer',
      status: 'pending',
      isCurrentUser: false,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      knowledgeBaseId: secondId,
      userId: null,
      email: 'invalid',
      displayName: null,
      role: 'viewer',
      status: 'pending',
      isCurrentUser: false,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
  },
  V3KnowledgeTaskTypeSchema: { valid: 'compilation', invalid: 'export' },
  V3KnowledgeScheduleExpressionSchema: { valid: '0 9 * * 1-5', invalid: 'daily at nine' },
  V3CreateKnowledgeScheduleSchema: {
    valid: { taskType: 'lint', schedule: '0 9 * * 1-5' },
    invalid: { taskType: 'lint', schedule: 'daily at nine' },
  },
  V3UpdateKnowledgeScheduleSchema: {
    valid: { enabled: false },
    invalid: { enabled: 'false' },
  },
  V3KnowledgeScheduleSchema: {
    valid: {
      id: firstId,
      knowledgeBaseId: secondId,
      taskType: 'source_refresh',
      schedule: '0 9 * * 1-5',
      timezone: 'Asia/Shanghai',
      enabled: true,
      lastRunAt: null,
      lastRunState: 'never',
      failureDetail: null,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      knowledgeBaseId: secondId,
      taskType: 'source_refresh',
      schedule: '0 9 * * 1-5',
      timezone: '',
      enabled: true,
      lastRunAt: null,
      lastRunState: 'never',
      failureDetail: null,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
  },
  V3KnowledgeScheduleRunSchema: {
    valid: {
      id: firstId,
      knowledgeBaseId: secondId,
      scheduledTaskId: thirdId,
      taskType: 'lint',
      status: 'success',
      reportMarkdown: '# Knowledge lint report',
      errorMessage: null,
      scheduledFor: occurredAt,
      createdAt: occurredAt,
      startedAt: occurredAt,
      finishedAt: occurredAt,
    },
    invalid: {
      id: firstId,
      knowledgeBaseId: secondId,
      scheduledTaskId: thirdId,
      taskType: 'lint',
      status: 'complete',
      reportMarkdown: null,
      errorMessage: null,
      scheduledFor: occurredAt,
      createdAt: occurredAt,
      startedAt: null,
      finishedAt: null,
    },
  },
  V3KnowledgeCompilationTemplateSchema: {
    valid: 'multi_repo_wiki',
    invalid: 'other',
  },
  V3KnowledgeSettingsSchema: {
    valid: {
      knowledgeBaseId: firstId,
      compilationTemplate: 'multi_repo_wiki',
      appendPrompt: 'Only extract architecture evidence.',
      customPrompt: '',
      autoCompile: true,
      autoCompileDelayMinutes: 1,
      lastCompiledAt: null,
      updatedAt: occurredAt,
    },
    invalid: {
      knowledgeBaseId: firstId,
      compilationTemplate: 'other',
      appendPrompt: '',
      customPrompt: '',
      autoCompile: true,
      autoCompileDelayMinutes: 1,
      lastCompiledAt: null,
      updatedAt: occurredAt,
    },
  },
  V3UpdateKnowledgeSettingsSchema: {
    valid: {
      compilationTemplate: 'custom',
      appendPrompt: '',
      customPrompt: 'Generate only the requested evidence card.',
      autoCompile: true,
      autoCompileDelayMinutes: 30,
    },
    invalid: {
      compilationTemplate: 'llm_wiki',
      appendPrompt: '',
      customPrompt: '',
      autoCompile: true,
      autoCompileDelayMinutes: 5,
    },
  },
  V3CompileKnowledgeBaseSchema: {
    valid: { mode: 'full' },
    invalid: { mode: 'partial' },
  },
  V3RenameKnowledgeBaseSchema: {
    valid: { name: 'Renamed Knowledge' },
    invalid: { name: '' },
  },
  V3KnowledgeBindingInputSchema: {
    valid: { wakerId: firstId, expectedConfigurationVersionId: secondId },
    invalid: { wakerId: 'invalid', expectedConfigurationVersionId: secondId },
  },
  V3KnowledgeBindingSchema: {
    valid: {
      versionId: firstId,
      knowledgeBaseId: secondId,
      wakerId: thirdId,
      knowledgeVersion: 1,
      createdBy: firstId,
      createdAt: occurredAt,
    },
    invalid: {
      versionId: firstId,
      knowledgeBaseId: secondId,
      wakerId: thirdId,
      knowledgeVersion: -1,
      createdBy: firstId,
      createdAt: occurredAt,
    },
  },
  V3SkillMarketplaceCategorySchema: { valid: 'devops', invalid: 'games' },
  V3SkillMarketplaceSortSchema: { valid: 'hottest', invalid: 'popular' },
  V3SkillPackagePreparationSourceSchema: { valid: 'upload', invalid: 'remote' },
  V3SkillPackagePreparationSchema: {
    valid: {
      id: firstId,
      source: 'upload',
      name: 'Evidence Review',
      description: 'Reviews evidence.',
      fileName: 'evidence.zip',
      mediaType: 'application/zip',
      packageSha256: requestHash,
      contentSha256: requestHash,
      sizeBytes: 512,
      selfEvolution: false,
      expiresAt: occurredAt,
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      source: 'upload',
      name: '',
      description: 'Reviews evidence.',
      fileName: 'evidence.zip',
      mediaType: 'application/zip',
      packageSha256: requestHash,
      contentSha256: requestHash,
      sizeBytes: 512,
      selfEvolution: false,
      expiresAt: occurredAt,
      createdAt: occurredAt,
    },
  },
  V3SkillMarketplaceItemSchema: {
    valid: {
      id: 'official-skill',
      name: 'Official Skill',
      localizedName: '官方技能',
      description: 'Verified official marketplace metadata.',
      localizedDescription: '经过验证的官方市场元数据。',
      author: 'Qoder',
      category: 'devops',
      iconUrl: 'https://example.com/icon.png',
      installCount: 10,
      recommended: true,
      updatedAt: occurredAt,
    },
    invalid: { id: '', name: '', installCount: -1, updatedAt: 'invalid' },
  },
  V3SkillMarketplaceDetailSchema: {
    valid: {
      id: 'official-skill',
      name: 'Official Skill',
      localizedName: null,
      description: 'Verified official marketplace metadata.',
      localizedDescription: null,
      author: 'Qoder',
      authorName: 'Qoder Team',
      category: 'devops',
      iconUrl: null,
      installCount: 10,
      updatedAt: occurredAt,
      version: '1.0.0',
      recommended: true,
      readmeMarkdown: '# Official Skill\n\nVerified instructions.',
    },
    invalid: { id: '', name: '', version: '', readmeMarkdown: '' },
  },
  V3SkillMarketplacePageSchema: {
    valid: {
      items: [
        {
          id: 'official-skill',
          name: 'Official Skill',
          localizedName: '官方技能',
          description: 'Verified official marketplace metadata.',
          localizedDescription: '经过验证的官方市场元数据。',
          author: 'Qoder',
          category: 'devops',
          iconUrl: null,
          installCount: 10,
          recommended: false,
          updatedAt: occurredAt,
        },
      ],
      page: 1,
      pageSize: 12,
      total: 1,
      lastPage: 1,
    },
    invalid: { items: [], page: 0, pageSize: 25, total: -1, lastPage: 0 },
  },
  V3InstallMarketplaceSkillSchema: {
    valid: { selfEvolution: false, expectedConfigurationVersionId: firstId },
    invalid: { selfEvolution: 'yes', expectedConfigurationVersionId: 'invalid' },
  },
  V3SkillInstallationSchema: {
    valid: {
      id: firstId,
      wakerId: secondId,
      currentVersionId: thirdId,
      name: 'Evidence Review',
      description: 'Reviews real release evidence.',
      source: 'markdown',
      status: 'installed',
      version: 1,
      contentSha256: requestHash,
      fileName: 'SKILL.md',
      selfEvolution: false,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, wakerId: secondId, name: '', status: 'pretending', version: 0 },
  },
  V3SkillVersionSchema: {
    valid: skillVersion,
    invalid: { ...skillVersion, number: 0, changeSummary: '' },
  },
  V3SkillDiffLineSchema: {
    valid: { operation: 'added', content: 'Check every claim.', oldLineNumber: null, newLineNumber: 2 },
    invalid: { operation: 'changed', content: 'Invalid', oldLineNumber: 0, newLineNumber: 0 },
  },
  V3SkillComparisonSchema: {
    valid: {
      from: skillVersion,
      to: { ...skillVersion, id: secondId, number: 2, isCurrent: true },
      addedLines: 1,
      removedLines: 0,
      unchangedLines: 1,
      files: [
        {
          path: 'SKILL.md',
          status: 'modified',
          binary: false,
          addedLines: 1,
          removedLines: 0,
          unchangedLines: 1,
          oldSizeBytes: null,
          newSizeBytes: 0,
          oldLineCount: 1,
          newLineCount: 2,
          lines: [
            { operation: 'unchanged', content: '# Evidence Review', oldLineNumber: 1, newLineNumber: 1 },
            { operation: 'added', content: 'Check every claim.', oldLineNumber: null, newLineNumber: 2 },
          ],
        },
      ],
    },
    invalid: { from: skillVersion, to: skillVersion, addedLines: -1, lines: [] },
  },
  V3SkillFileDiffSchema: {
    valid: {
      path: 'reference.md',
      status: 'added',
      binary: false,
      addedLines: 0,
      removedLines: 0,
      unchangedLines: 0,
      oldSizeBytes: null,
      newSizeBytes: 0,
      oldLineCount: 0,
      newLineCount: 0,
      lines: [],
    },
    invalid: { path: 'reference.md', status: 'unknown' },
  },
  V3SkillLifecycleInputSchema: {
    valid: {
      action: 'rollback',
      targetVersionId: secondId,
      expectedVersion: 1,
      expectedConfigurationVersionId: firstId,
    },
    invalid: { action: 'rollback', expectedVersion: 1, expectedConfigurationVersionId: firstId },
  },
  V3ConnectorTransportSchema: { valid: 'streamable_http', invalid: 'websocket' },
  V3CreateConnectorSchema: {
    valid: {
      name: 'Reference MCP',
      transport: 'streamable_http',
      url: 'https://example.com/mcp',
      timeoutSeconds: 30,
    },
    invalid: { name: '', transport: 'websocket', timeoutSeconds: 0 },
  },
  V3CreateWakerConnectorSchema: {
    valid: {
      name: 'Reference MCP',
      transport: 'streamable_http',
      url: 'https://example.com/mcp',
      timeoutSeconds: 30,
      expectedConfigurationVersionId: firstId,
    },
    invalid: {
      name: 'Reference MCP',
      transport: 'streamable_http',
      timeoutSeconds: 30,
      expectedConfigurationVersionId: 'invalid',
    },
  },
  V3UpdateConnectorSchema: {
    valid: {
      url: 'https://example.com/mcp',
      environment: {},
      timeoutSeconds: 30,
      expectedVersion: 1,
      expectedConfigurationVersionId: firstId,
    },
    invalid: {
      url: 'not-a-url',
      environment: {},
      timeoutSeconds: 0,
      expectedVersion: 0,
      expectedConfigurationVersionId: 'invalid',
    },
  },
  V3ConnectorToolSchema: {
    valid: { name: 'search', description: 'Search source records.' },
    invalid: { name: '', description: 'Invalid tool.' },
  },
  V3ConnectorDiagnosticSchema: {
    valid: {
      status: 'ready',
      message: 'MCP initialized.',
      tools: [{ name: 'search', description: 'Search source records.' }],
      checkedAt: occurredAt,
    },
    invalid: { status: 'connected', message: '', tools: [], checkedAt: 'invalid' },
  },
  V3ConnectorSchema: {
    valid: {
      id: firstId,
      wakerId: secondId,
      currentVersionId: thirdId,
      name: 'Reference MCP',
      transport: 'streamable_http',
      command: null,
      arguments: [],
      url: 'https://example.com/mcp',
      credentialKeys: [],
      selectedTools: ['search'],
      timeoutSeconds: 30,
      headersHelper: '',
      status: 'ready',
      diagnostic: {
        status: 'ready',
        message: 'MCP initialized.',
        tools: [{ name: 'search', description: 'Search source records.' }],
        checkedAt: occurredAt,
      },
      version: 2,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, wakerId: secondId, name: '', transport: 'websocket', version: 0 },
  },
  V3ConnectorToolSelectionInputSchema: {
    valid: {
      expectedVersion: 2,
      expectedConfigurationVersionId: firstId,
      selectedTools: ['search'],
    },
    invalid: { expectedVersion: 0, expectedConfigurationVersionId: 'invalid', selectedTools: [''] },
  },
  V3ConnectorLifecycleInputSchema: {
    valid: {
      action: 'disable',
      expectedVersion: 2,
      expectedConfigurationVersionId: firstId,
    },
    invalid: { action: 'archive', expectedVersion: 0, expectedConfigurationVersionId: 'invalid' },
  },
  V3ImProviderSchema: { valid: 'feishu', invalid: 'slack' },
  V3ImAccessPolicySchema: { valid: 'approval_required', invalid: 'public' },
  V3ImChannelDiagnosticSchema: {
    valid: { status: 'ready', message: 'Feishu credentials validated successfully.', checkedAt: occurredAt },
    invalid: { status: 'connected', message: '', checkedAt: 'invalid' },
  },
  V3ImChannelSchema: {
    valid: {
      id: firstId,
      currentVersionId: secondId,
      wakerId: thirdId,
      provider: 'feishu',
      displayName: 'Feishu',
      accessPolicy: 'approval_required',
      autoSendArtifacts: true,
      enabled: true,
      cardType: null,
      credentialKeys: ['APP_ID', 'APP_SECRET'],
      status: 'ready',
      diagnostic: {
        status: 'ready',
        message: 'Feishu credentials validated successfully.',
        checkedAt: occurredAt,
      },
      version: 2,
      createdAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, provider: 'slack', displayName: '', version: 0 },
  },
  V3CreateImChannelSchema: {
    valid: {
      provider: 'feishu',
      wakerId: thirdId,
      displayName: 'Feishu',
      accessPolicy: 'approval_required',
      autoSendArtifacts: true,
      enabled: true,
      credentials: { APP_ID: 'cli_example', APP_SECRET: 'secret-value' },
    },
    invalid: {
      provider: 'feishu',
      wakerId: 'invalid',
      displayName: '',
      accessPolicy: 'public',
      autoSendArtifacts: true,
      enabled: true,
      credentials: {},
    },
  },
  V3UpdateImChannelSchema: {
    valid: {
      provider: 'feishu',
      wakerId: thirdId,
      displayName: 'Feishu',
      accessPolicy: 'open_access',
      autoSendArtifacts: true,
      enabled: true,
      credentials: { APP_ID: 'cli_example', APP_SECRET: 'secret-value' },
      expectedVersion: 1,
    },
    invalid: {
      provider: 'feishu',
      wakerId: thirdId,
      displayName: 'Feishu',
      accessPolicy: 'open_access',
      autoSendArtifacts: true,
      enabled: true,
      credentials: {},
      expectedVersion: 0,
    },
  },
  V3ImChannelLifecycleInputSchema: {
    valid: { action: 'disable', expectedVersion: 1 },
    invalid: { action: 'archive', expectedVersion: 0 },
  },
  V3ImQrAuthStartInputSchema: {
    valid: { provider: 'feishu' },
    invalid: { provider: 'wechat' },
  },
  V3ImQrAuthSessionSchema: {
    valid: {
      sessionId: firstId,
      provider: 'feishu',
      verificationUrl: 'https://accounts.feishu.cn/device?code=example',
      pollAfterMs: 5_000,
      expiresAt: occurredAt,
    },
    invalid: { sessionId: 'invalid', provider: 'wechat', verificationUrl: 'not-a-url', pollAfterMs: 0 },
  },
  V3ImQrAuthPollInputSchema: {
    valid: { sessionId: firstId },
    invalid: { sessionId: 'invalid' },
  },
  V3ImQrAuthPollResultSchema: {
    valid: { status: 'pending', pollAfterMs: 5_000, channel: null },
    invalid: { status: 'authorized', pollAfterMs: 0, channel: null },
  },
  V3ImConversationSchema: {
    valid: {
      id: firstId,
      channelId: secondId,
      channelName: 'Feishu',
      provider: 'feishu',
      name: 'Engineering',
      type: 'group',
      source: 'feishu',
      wakerId: thirdId,
      groupId: null,
      workspaceReferenceId: null,
      model: 'deepseek-chat',
      atWaker: false,
      pairingVersion: 1,
      status: 'active',
      lastEventAt: occurredAt,
      updatedAt: occurredAt,
    },
    invalid: { id: firstId, channelId: secondId, name: '', type: 'room', status: 'paired' },
  },
  V3ImPairingRequestSchema: {
    valid: {
      id: firstId,
      channelId: secondId,
      conversationId: thirdId,
      conversationName: 'Engineering',
      provider: 'feishu',
      conversationType: 'group',
      status: 'pending',
      version: 1,
      requestedAt: occurredAt,
      resolvedAt: null,
      resolvedBy: null,
    },
    invalid: { id: firstId, status: 'open', version: 0, requestedAt: 'invalid' },
  },
  V3CreateImPairingSchema: {
    valid: {
      conversationId: firstId,
      wakerId: secondId,
      groupId: null,
      workspaceReferenceId: null,
      model: 'deepseek-chat',
      atWaker: false,
    },
    invalid: { conversationId: 'invalid', wakerId: secondId, model: '', atWaker: false },
  },
  V3CreateManualImPairingSchema: {
    valid: {
      channelId: firstId,
      displayName: 'Direct User',
      wakerId: secondId,
      groupId: null,
      workspaceReferenceId: null,
      model: 'deepseek-chat',
      atWaker: false,
      type: 'direct',
      receiveIdType: 'open_id',
      receiveId: 'ou_direct_user',
    },
    invalid: {
      channelId: firstId,
      displayName: '',
      wakerId: null,
      groupId: thirdId,
      workspaceReferenceId: null,
      model: '',
      atWaker: false,
      type: 'group',
      receiveIdType: 'open_id',
      receiveId: '',
    },
  },
  V3UpdateImPairingSchema: {
    valid: {
      wakerId: secondId,
      groupId: null,
      workspaceReferenceId: null,
      model: 'deepseek-chat',
      atWaker: true,
      expectedVersion: 1,
    },
    invalid: {
      wakerId: secondId,
      groupId: null,
      workspaceReferenceId: null,
      model: '',
      atWaker: true,
      expectedVersion: 0,
    },
  },
  V3ImPairingLifecycleInputSchema: {
    valid: { action: 'pause', expectedVersion: 1 },
    invalid: { action: 'archive', expectedVersion: 0 },
  },
  V3ResolveImPairingRequestSchema: {
    valid: { decision: 'reject', expectedVersion: 1 },
    invalid: { decision: 'approve', expectedVersion: 0 },
  },
  V3BootstrapSchema: {
    valid: {
      principal,
      workspace: {
        id: secondId,
        name: 'Default Workspace',
        status: 'active',
        defaultTimezone: 'Asia/Shanghai',
      },
      capabilities: { local: false, cloud: true },
      navigation: { wakers: 2, tasks: 0 },
      aiGatewayModel: 'gateway-test-model',
      aiGatewayModels: ['gateway-test-model', 'gateway-model-b'],
    },
    invalid: { principal, workspace: {}, capabilities: {}, navigation: {} },
  },
  V3AiGatewayVirtualKeyStatusSchema: {
    valid: { configured: true, hint: 'sk********cd' },
    invalid: { configured: true, hint: 'raw-virtual-key' },
  },
  V3AiGatewayVirtualKeyClaimResponseSchema: {
    valid: { status: 'ready', configured: true, hint: 'sk********cd' },
    invalid: { status: 'ready', configured: false },
  },
  V3AiGatewayVirtualKeyInputSchema: {
    valid: { virtualKey: 'sk-test-virtual-key' },
    invalid: { virtualKey: 'contains whitespace' },
  },
  V3UnreadQuerySchema: {
    valid: { wakerIds: [firstId], groupIds: [] },
    invalid: { wakerIds: ['emp_01kzr3qgdqqqy3qg43f7wxwt64'], groupIds: [] },
  },
  V3WakerUnreadSchema: {
    valid: { wakerId: firstId, unreadCount: 1, normalUnreadCount: 1, triggerUnreadCount: 0 },
    invalid: { wakerId: firstId, unreadCount: -1, normalUnreadCount: 0, triggerUnreadCount: 0 },
  },
  V3GroupUnreadSchema: {
    valid: { groupId: firstId, unreadCount: 0 },
    invalid: { groupId: firstId, unreadCount: -1 },
  },
  V3UnreadCountsSchema: {
    valid: { wakers: [], groups: [] },
    invalid: { wakers: {}, groups: [] },
  },
  V3MarkSubjectReadSchema: {
    valid: { subjectType: 'waker', subjectId: firstId },
    invalid: { subjectType: 'employee', subjectId: firstId },
  },
  V3WakerBuiltinCapabilitiesSchema: {
    valid: contracts.defaultWakerBuiltinCapabilities(),
    invalid: {
      memory: true,
      knowledge: true,
      imChannelSend: true,
      groupChatContext: true,
      wakerMemory: true,
    },
  },
  V3BrowserConnectorManualProvenanceSchema: {
    valid: {
      source: 'manual_fallback',
      version: '1.5.0',
      manifestSha256: requestHash,
      observedAt: occurredAt,
    },
    invalid: {
      source: 'chrome_web_store',
      version: '1.5.0',
      manifestSha256: requestHash,
      observedAt: occurredAt,
    },
  },
  V3BrowserConnectorCandidateProvenanceSchema: {
    valid: {
      source: 'candidate_manual_package',
      extensionId: contracts.V3_BROWSER_CONNECTOR_CANDIDATE_EXTENSION_ID,
      version: '1.5.0',
      manifestSha256: requestHash,
      observedAt: occurredAt,
    },
    invalid: {
      source: 'candidate_manual_package',
      extensionId: 'untrusted-extension',
      version: '1.5.0',
      manifestSha256: requestHash,
      observedAt: occurredAt,
    },
  },
  V3BrowserConnectorLiveProvenanceSchema: {
    valid: {
      source: 'chrome_web_store',
      extensionId: contracts.V3_BROWSER_CONNECTOR_CHROME_EXTENSION_ID,
      version: '1.6.0',
      observedAt: occurredAt,
    },
    invalid: {
      source: 'chrome_web_store',
      extensionId: 'untrusted-extension',
      version: '1.6.0',
      observedAt: occurredAt,
    },
  },
  V3BrowserConnectorFallbackSchema: {
    valid: {
      status: 'available',
      displayPath: 'C:\\Users\\owner\\.qoderwake-cn\\data\\browser-connector\\chrome-extension',
      provenance: {
        source: 'manual_fallback',
        version: '1.5.0',
        manifestSha256: requestHash,
        observedAt: occurredAt,
      },
    },
    invalid: {
      status: 'available',
      displayPath: 'C:\\extension',
      provenance: {
        source: 'chrome_web_store',
        version: '1.6.0',
        observedAt: occurredAt,
      },
    },
  },
  V3BrowserConnectorLiveSchema: {
    valid: {
      connectionStatus: 'connected',
      ready: true,
      relayRunning: true,
      relayEnabled: true,
      protocolFamily: 'v2',
      provenance: {
        source: 'chrome_web_store',
        extensionId: contracts.V3_BROWSER_CONNECTOR_CHROME_EXTENSION_ID,
        version: '1.6.0',
        observedAt: occurredAt,
      },
    },
    invalid: {
      connectionStatus: 'connected',
      ready: true,
      relayRunning: false,
      relayEnabled: true,
      protocolFamily: 'v2',
      provenance: null,
    },
  },
  V3BrowserConnectorGrantSchema: {
    valid: { status: 'none' },
    invalid: { status: 'active-tab' },
  },
  V3BrowserConnectorEnablementSchema: {
    valid: { wakerId: firstId, enabled: false, version: 1, updatedAt: occurredAt },
    invalid: { wakerId: firstId, enabled: false, version: 0, updatedAt: occurredAt },
  },
  V3SkillEvolutionPolicySchema: {
    valid: { wakerId: firstId, enabled: true, version: 1, updatedAt: occurredAt },
    invalid: { wakerId: firstId, enabled: true, version: 0, updatedAt: occurredAt },
  },
  V3UpdateSkillEvolutionPolicySchema: {
    valid: { enabled: false, expectedVersion: 1 },
    invalid: { enabled: false, expectedVersion: 0 },
  },
  V3UpdateBrowserConnectorEnablementSchema: {
    valid: { enabled: true, expectedVersion: 1 },
    invalid: { enabled: true, expectedVersion: 0 },
  },
  V3BrowserConnectorStateSchema: {
    valid: contracts.createV3BrowserConnectorWebNoopState({
      wakerId: firstId,
      enabled: false,
      version: 1,
      updatedAt: occurredAt,
    }),
    invalid: {
      ...contracts.createV3BrowserConnectorWebNoopState({
        wakerId: firstId,
        enabled: false,
        version: 1,
        updatedAt: occurredAt,
      }),
      tabId: 'forbidden',
    },
  },
  V3CreateExportSchema: {
    valid: { resourceType: 'wakers', fields: ['id', 'name'], format: 'csv' },
    invalid: { resourceType: 'wakers', fields: [], format: 'csv' },
  },
  V3ExportJobSchema: {
    valid: {
      id: firstId,
      resourceType: 'wakers',
      fields: ['id', 'name'],
      format: 'csv',
      status: 'queued',
      schemaVersion: 1,
      rowCount: 0,
      sha256: null,
      artifactId: null,
      createdAt: occurredAt,
    },
    invalid: {
      id: firstId,
      resourceType: 'wakers',
      fields: ['id'],
      format: 'xml',
      status: 'queued',
    },
  },
  V3DesktopMachineRegistrationInputSchema: {
    valid: {
      machine_name: 'DESKTOP-REFERENCE',
      machine_id: firstId,
      client_version: '0.1.0-beta.14',
      platform: 'win32',
      architecture: 'x64',
    },
    invalid: {
      machine_name: '',
      machine_id: firstId,
      client_version: '0.1.0-beta.14',
      platform: 'browser',
      architecture: 'x64',
    },
  },
  V3RemoteMachineRegistrationResultSchema: {
    valid: { machine_secret: remoteLeaseToken },
    invalid: { machine_secret: 'short' },
  },
  V3RemoteConversationLeaseSchema: {
    valid: remoteConversationLease,
    invalid: { ...remoteConversationLease, epoch: 0 },
  },
  V3RemoteConversationRunWorkDataSchema: {
    valid: remoteConversationRunWorkData,
    invalid: { ...remoteConversationRunWorkData, trigger_message_ids: [] },
  },
  V3RemoteConversationRunWorkSchema: {
    valid: remoteConversationRunWork,
    invalid: { ...remoteConversationRunWork, state: 'pending' },
  },
  V3RemoteWorkPollResponseSchema: {
    valid: remoteConversationRunWork,
    invalid: { unexpected: true },
  },
  V3RemoteWorkAckInputSchema: {
    valid: { work_id: firstId },
    invalid: { work_id: 'not-a-uuid' },
  },
  V3RemoteConversationAcceptInputSchema: {
    valid: { ...remoteConversationLease, idempotency_key: `accept:${firstId}:1` },
    invalid: { ...remoteConversationLease, idempotency_key: '' },
  },
  V3RemoteConversationFrameSchema: {
    valid: { seq: 1, kind: 'product_event', payload: { type: 'run.started' } },
    invalid: { seq: 0, kind: 'product_event', payload: {} },
  },
  V3RemoteConversationFramesInputSchema: {
    valid: {
      ...remoteConversationLease,
      frames: [{ seq: 1, kind: 'product_event', payload: { type: 'run.started' } }],
    },
    invalid: { ...remoteConversationLease, frames: [] },
  },
  V3RemoteConversationCompleteInputSchema: {
    valid: {
      ...remoteConversationLease,
      idempotency_key: `complete:${firstId}:1`,
      result_message_id: secondId,
    },
    invalid: { ...remoteConversationLease, idempotency_key: '' },
  },
  V3RemoteConversationFailInputSchema: {
    valid: {
      ...remoteConversationLease,
      idempotency_key: `fail:${firstId}:1`,
      error: { code: 'provider_stream', message: 'The bounded stream ended early.' },
    },
    invalid: {
      ...remoteConversationLease,
      idempotency_key: `fail:${firstId}:1`,
      error: { code: 'provider_stream', message: '' },
    },
  },
  V3RemoteConversationCancelAckInputSchema: {
    valid: { ...remoteConversationLease, idempotency_key: `cancel-ack:${firstId}:1` },
    invalid: { ...remoteConversationLease, idempotency_key: '' },
  },
  V3RemoteConversationSnapshotSchema: {
    valid: {
      conversation: { id: secondId, kind: 'direct_conversation', title: 'Remote evidence' },
      execution: {
        prompt: 'Review the bounded evidence.',
        system_prompt: 'Review without using tools.',
        model: 'gateway-test-model',
        response_language: 'zh-CN',
      },
    },
    invalid: {
      conversation: { id: secondId, kind: 'direct_conversation', title: 'Remote evidence' },
      execution: {
        prompt: 'Review the bounded evidence.',
        system_prompt: '',
        model: 'gateway-test-model',
      },
    },
  },
  V3ReadTaskResultSchema: {
    valid: { resultVersion: 'completed:1' },
    invalid: { resultVersion: '' },
  },
  V3RemoteAttachmentSchema: {
    valid: {
      id: firstId,
      originalName: 'evidence.txt',
      mediaType: 'text/plain',
      sizeBytes: 21,
      sha256: requestHash,
    },
    invalid: {
      id: firstId,
      originalName: 'evidence.txt',
      mediaType: 'text/plain',
      sizeBytes: 0,
      sha256: requestHash,
    },
  },
  V3RemoteArtifactMetadataSchema: {
    valid: {
      kind: 'artifact',
      artifactType: 'document',
      source: 'present_files',
      toolName: 'present_files',
      title: 'Evidence',
      description: null,
      relativePath: 'evidence.txt',
      mediaType: 'text/plain',
    },
    invalid: {
      kind: 'artifact',
      artifactType: 'document',
      source: 'unknown',
      toolName: null,
      title: 'Evidence',
      description: null,
      relativePath: 'evidence.txt',
      mediaType: 'text/plain',
    },
  },
  V3RemoteToolApprovalInputSchema: {
    valid: {
      ...remoteConversationLease,
      command: 'write evidence.txt',
      target: 'evidence.txt',
      risk: 'write',
      request_hash: requestHash,
      policy_versions: [{ id: secondId, version: 1 }],
    },
    invalid: {
      ...remoteConversationLease,
      command: 'write evidence.txt',
      target: 'evidence.txt',
      risk: 'write',
      request_hash: requestHash,
      policy_versions: [],
    },
  },
  V3RemoteToolApprovalStatusInputSchema: {
    valid: { ...remoteConversationLease, approval_id: firstId },
    invalid: { ...remoteConversationLease, approval_id: 'not-a-uuid' },
  },
  V3DesktopMachineInventorySchema: {
    valid: {
      items: [
        {
          id: firstId,
          deviceName: 'Windows',
          clientVersion: '1.0.0',
          platform: 'win32',
          architecture: 'x64',
          registeredAt: occurredAt,
          lastSeenAt: occurredAt,
          lastPollAt: null,
          pollCount: 0,
          version: 1,
          wakerCount: 1,
          online: false,
        },
      ],
    },
    invalid: { items: [{ id: firstId, online: 'yes' }] },
  },
  V3DesktopMachineSchema: {
    valid: {
      id: firstId,
      deviceName: 'DESKTOP-REFERENCE',
      clientVersion: '0.1.0-beta.14',
      platform: 'win32',
      architecture: 'x64',
      registeredAt: occurredAt,
      lastSeenAt: occurredAt,
      lastPollAt: null,
      pollCount: 0,
      version: 1,
    },
    invalid: {
      id: firstId,
      deviceName: '',
      clientVersion: '0.1.0-beta.14',
      platform: 'browser',
      architecture: 'x64',
      registeredAt: occurredAt,
      lastSeenAt: occurredAt,
      lastPollAt: null,
      pollCount: -1,
      version: 0,
    },
  },
  V3NetworkDiagnosticsSchema: {
    valid: {
      machineId: firstId,
      machine: {
        id: firstId,
        deviceName: 'DESKTOP-REFERENCE',
        clientVersion: '0.1.0-beta.14',
        platform: 'win32',
        architecture: 'x64',
        registeredAt: occurredAt,
        lastSeenAt: occurredAt,
        lastPollAt: occurredAt,
        pollCount: 3,
        version: 4,
      },
      checkedAt: occurredAt,
      checks: [
        { id: 'gateway', status: 'reachable', durationMs: 1, details: ['Status: 200 OK'] },
        { id: 'registration', status: 'reachable', durationMs: 0, details: ['registered'] },
        { id: 'work-return', status: 'reachable', durationMs: 0, details: ['polling'] },
      ],
    },
    invalid: {
      machineId: firstId,
      machine: null,
      checkedAt: occurredAt,
      checks: [
        { id: 'work-return', status: 'reachable', details: [] },
        { id: 'registration', status: 'reachable', details: [] },
        { id: 'gateway', status: 'reachable', details: [] },
      ],
    },
  },
};

describe('V3 TypeBox product contracts', () => {
  it('has a valid and invalid fixture for every exported V3 schema', () => {
    const schemas = Object.entries(contracts).filter(
      ([name, value]) => name.startsWith('V3') && name.endsWith('Schema') && typeof value === 'object',
    );

    expect(schemas.map(([name]) => name).sort()).toEqual(Object.keys(fixtures).sort());
    for (const [name, schema] of schemas) {
      const fixture = fixtures[name];
      expect(fixture, `missing fixture for ${name}`).toBeDefined();
      if (!fixture) continue;
      expect(Value.Check(schema as TSchema, fixture.valid), `${name} valid fixture`).toBe(true);
      expect(Value.Check(schema as TSchema, fixture.invalid), `${name} invalid fixture`).toBe(false);
    }
  });

  it('rejects the retired raw Marketplace Skill field while accepting prepared packages', () => {
    const base = {
      name: 'Backend role',
      summary: 'Backend delivery',
      identity: '',
      persona: '',
      bible: '',
      defaultQuestions: { EN: ['Review this API'], ZH: ['审查这个接口'] },
    };
    expect(
      Value.Check(contracts.V3CreateRoleTemplateSchema, {
        ...base,
        marketplaceSkillIds: ['legacy-name-only-id'],
      }),
    ).toBe(false);
    expect(
      Value.Check(contracts.V3CreateRoleTemplateSchema, {
        ...base,
        skillPackagePreparationIds: [firstId],
      }),
    ).toBe(true);
  });
  it('rejects unknown business fields and raw host paths', () => {
    expect(
      Value.Check(contracts.V3CreateWakerSchema, {
        ...createWaker,
        providerApiKey: 'must-not-cross-the-contract',
      }),
    ).toBe(false);
    expect(
      Value.Check(contracts.V3WorkspaceReferenceSchema, {
        id: firstId,
        kind: 'local_directory',
        displayName: 'workspace',
        availability: 'available',
        version: 1,
        createdAt: occurredAt,
        updatedAt: occurredAt,
        rawPath: 'C:\\private\\workspace',
      }),
    ).toBe(false);
  });

  it('accepts only fully declared Script or HTTP WakerFlow Actions', () => {
    expect(
      Value.Check(contracts.V3WorkflowNodeSchema, {
        id: 'notify',
        name: 'Notify',
        next: [],
        type: 'action',
        actionId: 'notify-script',
        actionType: 'script',
        command: 'node scripts/notify.mjs',
        args: ['{{args.deliveryId}}'],
      }),
    ).toBe(true);
    expect(
      Value.Check(contracts.V3WorkflowNodeSchema, {
        id: 'webhook',
        name: 'Webhook',
        next: [],
        type: 'action',
        actionId: 'delivery-webhook',
        actionType: 'http',
        url: 'https://actions.example.test/deliver',
        args: { deliveryId: '{{args.deliveryId}}' },
      }),
    ).toBe(true);
    expect(
      Value.Check(contracts.V3WorkflowNodeSchema, {
        id: 'placeholder',
        name: 'Placeholder',
        next: [],
        type: 'action',
        actionId: 'old-placeholder',
        input: {},
      }),
    ).toBe(false);
  });

  it('keeps the ports free of UI, Electron, Node, and infrastructure imports', async () => {
    const source = await readFile(resolve(import.meta.dirname, '../src/v3-ports.ts'), 'utf8');
    expect(source).not.toMatch(/from ['"](?:node:|react|electron|fastify|pg|ioredis|dockerode)/u);
    expect(source).not.toMatch(/\b(?:HTMLElement|ReactNode|BrowserWindow|WebContents|PoolClient)\b/u);
  });
});
