/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        base: {
          default: "var(--color-bg-base-default)",
          low: "var(--color-bg-base-default-low)",
          secondary: "var(--color-bg-base-secondary)",
          "secondary-alt": "var(--color-bg-base-secondary-alt)",
          tertiary: "var(--color-bg-base-tertiary)",
        },
        brand: {
          DEFAULT: "var(--color-bg-brand-default)",
          secondary: "var(--color-bg-brand-secondary)",
          tertiary: "var(--color-bg-brand-tertiary)",
          "alpha-strong": "var(--color-bg-alpha-brand-secondary)",
          "alpha-soft": "var(--color-bg-alpha-brand-tertiary)",
          text: "var(--color-text-brand-default)",
          line: "var(--color-border-brand-default)",
          ring: "var(--color-ring-brand)",
        },
        neutral: {
          4: "var(--color-bg-neutral-4)",
          8: "var(--color-bg-neutral-8)",
          12: "var(--color-bg-neutral-12)",
          16: "var(--color-bg-neutral-16)",
          20: "var(--color-bg-neutral-20)",
          40: "var(--color-text-neutral-40)",
          60: "var(--color-text-neutral-60)",
          80: "var(--color-text-neutral-80)",
          95: "var(--color-text-neutral-95)",
          inverse: "var(--color-text-neutral-inverse-95)",
        },
        danger: {
          DEFAULT: "var(--color-danger-default)",
          strong: "var(--color-danger-strong)",
          soft: "var(--color-danger-soft)",
          line: "var(--color-border-danger-default)",
          surface: "var(--color-bg-danger-surface)",
          chip: "var(--color-bg-danger-chip)",
          edge: "var(--color-border-danger-soft)",
        },
        success: {
          DEFAULT: "var(--color-success-default)",
          strong: "var(--color-success-strong)",
          surface: "var(--color-bg-success-surface)",
          chip: "var(--color-bg-success-chip)",
          edge: "var(--color-border-success-soft)",
        },
        utilities: {
          header: "var(--color-bg-utilities-header)",
          footer: "var(--color-bg-utilities-footer)",
          tab: "var(--color-bg-utilities-tab)",
        },
        agent: {
          mike: "var(--color-agent-mike)",
          iris: "var(--color-agent-iris)",
          emma: "var(--color-agent-emma)",
          bob: "var(--color-agent-bob)",
          alex: "var(--color-agent-alex)",
          idle: "var(--color-agent-idle)",
        },
      },
      fontFamily: {
        sans: [
          "IBM Plex Sans",
          "PingFang SC",
          "Microsoft YaHei",
          "Noto Sans SC",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        mono: ["IBM Plex Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontSize: {
        "2xs": ["10px", "14px"],
        xs: ["11px", "16px"],
        sm: ["12px", "18px"],
        base: ["14px", "20px"],
        md: ["15px", "22px"],
        lg: ["16px", "24px"],
        xl: ["18px", "26px"],
        "2xl": ["20px", "28px"],
        "3xl": ["24px", "32px"],
        h1: ["32px", "40px"],
        display: ["40px", "48px"],
      },
      spacing: {
        xxxs: "2px",
        xxs: "4px",
        xs: "6px",
        s: "8px",
        m: "12px",
        l: "16px",
        xl: "24px",
        xxl: "32px",
        xxxl: "48px",
        sidebar: "164px",
      },
      borderRadius: {
        m: "8px",
        l: "12px",
        xl: "16px",
        composer: "24px",
        full: "999px",
      },
      borderWidth: {
        hair: "0.667px",
      },
      boxShadow: {
        flat: "0 1px 4px rgba(12, 12, 12, 0.08)",
      },
      transitionTimingFunction: {
        ui: "cubic-bezier(0.4, 0, 0.2, 1)",
        "sidebar-expand": "cubic-bezier(0.01, 0.99, 0.49, 1.01)",
        "sidebar-collapse": "cubic-bezier(0.08, 0.57, 0.02, 1)",
      },
      transitionDuration: {
        ui: "150ms",
        "sidebar-expand": "820ms",
        "sidebar-collapse": "460ms",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.45" },
        },
      },
      animation: {
        shimmer: "shimmer 2.4s linear infinite",
        "fade-in": "fade-in 220ms cubic-bezier(0.4, 0, 0.2, 1) both",
        "pulse-soft": "pulse-soft 1.4s cubic-bezier(0.4, 0, 0.2, 1) infinite",
      },
    },
  },
  plugins: [],
};
