import base64
import hashlib
import json
import os
from pathlib import Path
import sqlite3
import struct
import time

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from app.models import Base, User, Project, Run
from app.sandbox.docker_driver import DockerDriver, run_bounded
from app.sandbox.grants import Grant
from app.sandbox.lifecycle import Lifecycle
from app.sandbox.registry import Registry

IMAGE = os.environ.get('ATOM_TEST_DOCKER_IMAGE')
pytestmark = pytest.mark.skipif(not IMAGE, reason='requires explicit pinned local Docker test image')


def test_real_export_storage_registration_then_confirmed_release(tmp_path):
    root = Path(__file__).resolve().parents[3]
    path = tmp_path / 'api.db'
    engine = create_engine('sqlite:///' + path.as_posix())
    Base.metadata.create_all(engine)
    with Session(engine) as s:
        s.add(User(id='owner', email='owner@example.invalid', name='Owner', password_hash='fixture'))
        s.flush()
        s.add(Project(id='p',user_id='owner',title='Fixture',prompt='fixture',active_run_id='run'))
        s.flush()
        s.add(Run(id='run',project_id='p',role='alex',model='fixture',status='running'))
        s.commit()
    engine.dispose()
    with sqlite3.connect(path) as db:
        schema = '\n'.join(db.iterdump())
    sources = {name: (root / f'backend/app/{name}.py').read_text(encoding='utf-8')
               for name in ('snapshots','artifacts','revisions')}
    sources.update({name: (root / f'backend/app/migrations/{filename}.py').read_text(encoding='utf-8')
                    for name,filename in (('migration','__init__'),('revision_v1','revision_v1'))})
    loader = '''
import base64,json,os,sqlite3,sys,time,types
from pathlib import Path
data=json.loads(sys.stdin.buffer.read());sources=data['sources']
app=types.ModuleType('app');app.__path__=[];sys.modules['app']=app
m=types.ModuleType('app.migrations');m.__path__=[];m.__package__=m.__name__;sys.modules[m.__name__]=m
v=types.ModuleType('app.migrations.revision_v1');sys.modules[v.__name__]=v
exec(compile(sources['revision_v1'],'revision_v1.py','exec'),v.__dict__)
exec(compile(sources['migration'],'migration.py','exec'),m.__dict__)
for name in ('snapshots','artifacts','revisions'):
    module=types.ModuleType('app.'+name);sys.modules[module.__name__]=module;setattr(app,name,module)
    exec(compile(sources[name],name+'.py','exec'),module.__dict__)
path=Path('/workspace/api.db');store_path=Path('/workspace/artifacts')
'''
    registry = Registry(tmp_path / 'broker.db')
    driver = DockerDriver(registry.broker_id, IMAGE)
    manifest = b'{"files":[],"version":1}'
    seed = b'ATOMSNAP1\n' + struct.pack('>I',len(manifest)) + manifest
    now = int(time.time())
    grant = Grant('g','o','p','run','a',1,hashlib.sha256(manifest).hexdigest(),now,now+180)
    with Lifecycle(registry, driver) as lifecycle:
        lifecycle.start()
        worker = lifecycle.provision(grant)
        lifecycle.seed(grant,seed)
        lifecycle.file_operation(grant,worker.id,'write','tool',{'op':'write','path':'app.txt','content':'actual generated bytes\n'})
        exported = lifecycle.export_checkpoint(grant)
        ledger_grant = Grant('ledger-g','o','ledger-p','ledger-r','ledger-a',1,grant.base_revision,now,now+180)
        ledger = driver.inspect(lifecycle.provision(ledger_grant))
        payload = json.dumps({'sources':sources,'schema':schema,'seed':base64.b64encode(seed).decode(),
            'output':base64.b64encode(exported.payload).decode(),'worker':worker.id,'grant':grant.jti,
            'deadline':grant.exp}).encode()
        def execute(body):
            status,out,err = run_bounded([driver.executable,'exec','-i',ledger.id,'python3','-I','-c',loader+body],
                                         input_data=payload,timeout=25)
            assert status == 0, err.decode('utf-8')
            return out.decode().strip()
        registered = execute('''
with sqlite3.connect(path) as db: db.executescript(data['schema'])
m.migrate(path,Path('/workspace/backup.db'))
store_path.mkdir(mode=0o700)
store=app.artifacts.ArtifactStore(store_path)
repo=app.revisions.RevisionRepository(path)
with sqlite3.connect(path) as db:
    workspace=db.execute('SELECT id FROM revision_workspaces').fetchone()[0]
base=store.put(base64.b64decode(data['seed']))
repo.bootstrap('owner',workspace,base)
attempt=repo.allocate('owner',workspace,'run','attempt',data['worker'],data['grant'],data['deadline'])
output=store.put(base64.b64decode(data['output']))
pid=os.fork()
if pid==0:
    repo.register('owner','attempt',data['worker'],data['grant'],output)
    os._exit(47)
assert os.waitpid(pid,0)[1]==47<<8
receipt=repo.receipt('owner','attempt',data['worker'],data['grant'])
assert receipt is not None and store.read(receipt.artifact_key)==base64.b64decode(data['output'])
assert repo.register('owner','attempt',data['worker'],data['grant'],output)==receipt
with sqlite3.connect(path) as db:
    assert db.execute('SELECT COUNT(*) FROM revision_outbox').fetchone()==(1,)
    assert db.execute('SELECT active_attempt_id FROM revision_workspaces').fetchone()==('attempt',)
print(receipt.snapshot_revision)
''')
        assert registered == exported.revision
        assert registry.find(worker.id).state == 'quiescing'
        lifecycle.release(grant,worker.id)
        assert registry.find(worker.id).state == 'terminated'
        assert driver.inspect(worker) is None
        assert execute('''
repo=app.revisions.RevisionRepository(path)
repo.observe_termination('owner','attempt',confirmed=True,outcome='succeeded')
with sqlite3.connect(path) as db:
    assert db.execute('SELECT active_attempt_id FROM revision_workspaces').fetchone()==(None,)
    assert db.execute('SELECT state,termination_state,outcome FROM revision_attempts').fetchone()==('closed','confirmed','succeeded')
    assert not db.execute('PRAGMA foreign_key_check').fetchall()
print('confirmed')
''') == 'confirmed'
    assert not driver.owned_inventory()
