import base64
import asyncio
from contextlib import contextmanager
import hashlib
import json
import os
from pathlib import Path
import sqlite3
import struct
import time
import secrets
import socket
import threading
from dataclasses import replace

import pytest
import uvicorn
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from app.models import Base, User, Project, Run
from app.revisions import Receipt
from app.sandbox.client import BrokerClient, BrokerClientError
from app.sandbox.config import BrokerConfig
from app.sandbox.docker_driver import DockerDriver, run_bounded
from app.sandbox.grants import Grant, GrantCodec
from app.sandbox.lifecycle import LifecycleError
from app.sandbox.registry import Registry, RegistryError
from app.sandbox.service import create_app

IMAGE = os.environ.get('ATOM_TEST_DOCKER_IMAGE')
pytestmark = pytest.mark.skipif(not IMAGE, reason='requires explicit pinned local Docker test image')


@contextmanager
def running_broker(path):
    config = BrokerConfig(path,IMAGE,secrets.token_urlsafe(32),secrets.token_urlsafe(32),sweep_seconds=60)
    app = create_app(config)
    listener = socket.socket()
    listener.bind(('127.0.0.1',0))
    server = uvicorn.Server(uvicorn.Config(app,log_level='error',access_log=False))
    thread = threading.Thread(target=server.run,kwargs={'sockets':[listener]},daemon=True)
    thread.start()
    try:
        deadline = time.monotonic()+15
        while not server.started and thread.is_alive() and time.monotonic()<deadline:
            time.sleep(0.02)
        assert server.started
        with asyncio.Runner() as runner:
            client = BrokerClient(f'http://127.0.0.1:{listener.getsockname()[1]}',config.admin_token,
                                  GrantCodec(config.grant_key.encode()))
            try:
                yield app.state.lifecycle, client, runner
            finally:
                runner.run(client.__aexit__())
    finally:
        server.should_exit = True
        thread.join(timeout=20)
        listener.close()
    assert not thread.is_alive()


@pytest.mark.parametrize('cancel_before_ack', [False, True])
def test_real_export_storage_registration_then_confirmed_release(tmp_path, cancel_before_ack):
    root = Path(__file__).resolve().parents[3]
    path = tmp_path / 'api.db'
    engine = create_engine('sqlite:///' + path.as_posix())
    Base.metadata.create_all(engine)
    with Session(engine) as s:
        s.add(User(id='owner', email='owner@example.invalid', name='Owner', password_hash='fixture'))
        s.flush()
        s.add(Project(id='p',user_id='owner',title='Fixture',prompt='fixture',active_run_id='run'))
        s.flush()
        s.add(Run(id='run',project_id='p',role='alex',model='fixture',status='running'))
        s.commit()
    engine.dispose()
    with sqlite3.connect(path) as db:
        schema = '\n'.join(db.iterdump())
    sources = {name: (root / f'backend/app/{name}.py').read_text(encoding='utf-8')
               for name in ('snapshots','artifacts','revisions')}
    sources.update({name: (root / f'backend/app/migrations/{filename}.py').read_text(encoding='utf-8')
                    for name,filename in (('migration','__init__'),('revision_v1','revision_v1'))})
    loader = '''
import base64,json,os,sqlite3,sys,time,types
from pathlib import Path
data=json.loads(sys.stdin.buffer.read());sources=data['sources']
app=types.ModuleType('app');app.__path__=[];sys.modules['app']=app
m=types.ModuleType('app.migrations');m.__path__=[];m.__package__=m.__name__;sys.modules[m.__name__]=m
v=types.ModuleType('app.migrations.revision_v1');sys.modules[v.__name__]=v
exec(compile(sources['revision_v1'],'revision_v1.py','exec'),v.__dict__)
exec(compile(sources['migration'],'migration.py','exec'),m.__dict__)
for name in ('snapshots','artifacts','revisions'):
    module=types.ModuleType('app.'+name);sys.modules[module.__name__]=module;setattr(app,name,module)
    exec(compile(sources[name],name+'.py','exec'),module.__dict__)
path=Path('/workspace/api.db');store_path=Path('/workspace/artifacts')
'''
    registry = Registry(tmp_path / 'broker.db')
    driver = DockerDriver(registry.broker_id, IMAGE)
    manifest = b'{"files":[],"version":1}'
    seed = b'ATOMSNAP1\n' + struct.pack('>I',len(manifest)) + manifest
    now = int(time.time())
    grant = Grant('g','o','p','run','attempt',1,hashlib.sha256(manifest).hexdigest(),now,now+180)
    with running_broker(registry.path) as (lifecycle, client, runner):
        provisioned = runner.run(client.provision(grant))
        worker = registry.find(provisioned.attempt_id)
        assert runner.run(client.provision(grant)) == provisioned
        runner.run(client.seed(grant,worker.id,seed))
        lifecycle.file_operation(grant,worker.id,'write','tool',{'op':'write','path':'app.txt','content':'actual generated bytes\n'})
        exported = runner.run(client.export(grant,worker.id))
        ledger_grant = Grant('ledger-g','o','ledger-p','ledger-r','ledger-a',1,grant.base_revision,now,now+180)
        ledger = driver.inspect(lifecycle.provision(ledger_grant))
        payload = json.dumps({'sources':sources,'schema':schema,'seed':base64.b64encode(seed).decode(),
            'output':base64.b64encode(exported.payload).decode(),'worker':worker.id,'grant':grant.jti,
            'deadline':grant.exp}).encode()
        def execute(body):
            status,out,err = run_bounded([driver.executable,'exec','-i',ledger.id,'python3','-I','-c',loader+body],
                                         input_data=payload,timeout=25)
            assert status == 0, err.decode('utf-8')
            return out.decode().strip()
        registered = execute('''
from dataclasses import asdict
with sqlite3.connect(path) as db: db.executescript(data['schema'])
m.migrate(path,Path('/workspace/backup.db'))
store_path.mkdir(mode=0o700)
store=app.artifacts.ArtifactStore(store_path)
repo=app.revisions.RevisionRepository(path)
with sqlite3.connect(path) as db:
    workspace=db.execute('SELECT id FROM revision_workspaces').fetchone()[0]
base=store.put(base64.b64decode(data['seed']))
repo.bootstrap('owner',workspace,base)
attempt=repo.allocate('owner',workspace,'run','attempt',data['worker'],data['grant'],data['deadline'])
output=store.put(base64.b64decode(data['output']))
pid=os.fork()
if pid==0:
    repo.register('owner','attempt',data['worker'],data['grant'],output)
    os._exit(47)
assert os.waitpid(pid,0)[1]==47<<8
receipt=repo.receipt('owner','attempt',data['worker'],data['grant'])
assert receipt is not None and store.read(receipt.artifact_key)==base64.b64decode(data['output'])
assert repo.register('owner','attempt',data['worker'],data['grant'],output)==receipt
with sqlite3.connect(path) as db:
    assert db.execute('SELECT COUNT(*) FROM revision_outbox').fetchone()==(1,)
    assert db.execute('SELECT active_attempt_id FROM revision_workspaces').fetchone()==('attempt',)
print(json.dumps(asdict(receipt)))
''')
        receipt = Receipt(**json.loads(registered))
        registered = receipt.snapshot_revision
        assert registered == exported.revision
        assert registry.find(worker.id).state == 'quiescing'
        for changed, digest in [(exported, '0'*64), (replace(exported,payload=exported.payload[:-1]),registered),
                                (replace(exported,attempt_id='other'),registered),
                                (replace(exported,attempt_version=exported.attempt_version+1),registered)]:
            with pytest.raises((LifecycleError, RegistryError)):
                lifecycle.confirm_checkpoint(grant,changed,registered_revision=digest)
            assert registry.find(worker.id).state == 'quiescing'
        if cancel_before_ack:
            assert runner.run(client.revoke(grant.jti)) == 'terminated'
            with pytest.raises(BrokerClientError) as denied:
                runner.run(client.confirm(grant,exported,receipt))
            assert denied.value.status == 409
            with pytest.raises(RegistryError, match='grant_revoked'):
                lifecycle.confirm_checkpoint(grant,exported,registered_revision=registered)
            assert registry.find(worker.id).checkpoint_revision is None
        else:
            for changed in (replace(receipt,attempt_id='other'),replace(receipt,artifact_key='0'*64)):
                with pytest.raises(BrokerClientError,match='invalid_broker_request'):
                    runner.run(client.confirm(grant,exported,changed))
            confirmed = runner.run(client.confirm(grant,exported,receipt))
            assert registry.find(worker.id).state == 'checkpointed' and confirmed.revision == registered
            assert runner.run(client.confirm(grant,exported,receipt)) == confirmed
            assert driver.inspect(worker).running
        assert runner.run(client.revoke(grant.jti)) == 'terminated'
        assert registry.find(worker.id).state == 'terminated'
        assert driver.inspect(worker) is None
        outcome = 'cancelled' if cancel_before_ack else 'succeeded'
        assert execute('outcome=' + repr(outcome) + '\n' + '''
repo=app.revisions.RevisionRepository(path)
repo.observe_termination('owner','attempt',confirmed=True,outcome=outcome)
with sqlite3.connect(path) as db:
    assert db.execute('SELECT active_attempt_id FROM revision_workspaces').fetchone()==(None,)
    assert db.execute('SELECT state,termination_state,outcome FROM revision_attempts').fetchone()==('closed','confirmed',outcome)
    assert db.execute('SELECT COUNT(*) FROM revision_receipts').fetchone()==(1,)
    assert not db.execute('PRAGMA foreign_key_check').fetchall()
print('confirmed')
''') == 'confirmed'
    assert not driver.owned_inventory()
