export const V3_BUILTIN_TOOL_GROUPS = {
  General: ['Agent', 'AskUserQuestion', 'ImageGen', 'ImageSearch', 'Skill'],
  shell: ['Bash'],
  file: ['Edit', 'Glob', 'Grep', 'NotebookEdit', 'Read', 'Write'],
  planning: ['EnterPlanMode', 'ExitPlanMode', 'TodoWrite'],
  network: ['WebFetch', 'WebSearch'],
} as const;

export interface V3ToolGuardRuleDefinition {
  id: string;
  category: string;
  severity: 'critical' | 'high';
  description: string;
  tools: readonly string[];
  parameter: string;
  remediation: string;
}

export const V3_TOOL_GUARD_RULES: readonly V3ToolGuardRuleDefinition[] = [
  {
    id: 'TOOL_CMD_FS_DESTRUCTION',
    category: '命令注入',
    severity: 'critical',
    description: '检测底层磁盘格式化或擦除命令',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截操作。数字员工不应格式化或覆盖原始块设备',
  },
  {
    id: 'TOOL_CMD_DANGEROUS_RM',
    category: '命令注入',
    severity: 'high',
    description: '检测可能导致数据丢失的 rm 命令',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '执行前与用户确认是否需要删除这些文件或目录',
  },
  {
    id: 'TOOL_CMD_DANGEROUS_MV',
    category: '命令注入',
    severity: 'high',
    description: '检测可能意外移动或覆盖文件的 mv 命令',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '执行前与用户确认是否需要移动或重命名文件',
  },
  {
    id: 'TOOL_CMD_DOS_FORK_BOMB',
    category: '资源滥用',
    severity: 'critical',
    description: '检测经典 Bash fork 炸弹与大规模进程终止',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '立即拦截。此类命令会导致主机系统崩溃',
  },
  {
    id: 'TOOL_CMD_SYSTEM_REBOOT',
    category: '资源滥用',
    severity: 'critical',
    description: '检测会终止主机系统的重启或关机命令',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截操作。数字员工不应重启或关闭系统',
  },
  {
    id: 'TOOL_CMD_SERVICE_RESTART',
    category: '资源滥用',
    severity: 'high',
    description: '检测可能中断系统服务的服务管理命令',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '与用户确认。重启服务可能导致停机或数据丢失',
  },
  {
    id: 'TOOL_CMD_PROCESS_KILL',
    category: '资源滥用',
    severity: 'high',
    description: '检测可能杀死关键进程的进程终止命令',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '与用户确认。终止进程可能导致数据丢失或系统不稳定',
  },
  {
    id: 'TOOL_CMD_PIPE_TO_SHELL',
    category: '代码执行',
    severity: 'critical',
    description: '检测下载远程脚本并直接执行的 curl | bash 模式',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '与用户确认。数字员工应先检查脚本再执行',
  },
  {
    id: 'TOOL_CMD_CONTROL_CHARS',
    category: '代码执行',
    severity: 'critical',
    description: '命令包含不可打印的控制字符，可能绕过安全检查',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截包含控制字符的命令，合法 shell 命令中不需要此类字符',
  },
  {
    id: 'TOOL_CMD_OBFUSCATED_EXEC',
    category: '代码执行',
    severity: 'high',
    description: '检测将 base64 解码结果直接管道到 shell 解释器执行',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截执行。数字员工应使用明文命令',
  },
  {
    id: 'TOOL_CMD_IFS_INJECTION',
    category: '代码执行',
    severity: 'high',
    description: '命令使用 $IFS 变量，可能绕过安全校验',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拒绝包含 IFS 操作的命令。合法命令不需要直接引用 $IFS',
  },
  {
    id: 'TOOL_CMD_UNICODE_WHITESPACE',
    category: '代码执行',
    severity: 'high',
    description: '命令包含 Unicode 空白字符，可能造成解析不一致',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截包含非 ASCII 空白的命令，改用标准空格',
  },
  {
    id: 'TOOL_CMD_JQ_SYSTEM',
    category: '代码执行',
    severity: 'high',
    description: 'jq 命令包含 system() 函数，可用于执行任意 shell 命令',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截使用 system() 的 jq 命令，jq 只应用于数据处理而非命令执行',
  },
  {
    id: 'TOOL_CMD_JQ_FILE_FLAGS',
    category: '代码执行',
    severity: 'high',
    description: 'jq 命令使用了可读取任意文件或加载外部代码的标志',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '与用户确认。这些 jq 标志可能访问预期范围之外的文件',
  },
  {
    id: 'TOOL_CMD_ZSH_DANGEROUS',
    category: '代码执行',
    severity: 'high',
    description: '命令使用了可绕过安全检查的 Zsh 专用内建功能',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截 Zsh 模块/内建命令，它们提供绕过常规权限检查的原始 I/O、网络和执行能力',
  },
  {
    id: 'TOOL_CMD_REVERSE_SHELL',
    category: '网络滥用',
    severity: 'critical',
    description: '检测建立反弹 shell 或未授权网络通道的行为',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截操作。数字员工不需要把交互式 shell 绑定到网络套接字',
  },
  {
    id: 'TOOL_WEBFETCH_LOCAL_LOOPBACK',
    category: '网络滥用',
    severity: 'high',
    description: '检测对本地回环或云 metadata 地址的 WebFetch，可能用于探测内网服务或窃取实例凭据',
    tools: ['WebFetch'],
    parameter: 'url',
    remediation: '拒绝对 loopback 及云厂商 metadata 地址的 fetch；如需要访问本地服务请显式在敏感清单外开白',
  },
  {
    id: 'TOOL_CMD_SYSTEM_TAMPERING',
    category: '敏感文件访问',
    severity: 'high',
    description: '检测访问 cron 任务、SSH 密钥或 sudo 权限文件（包含读取与修改）',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '与用户确认。凭据与调度相关文件应按敏感文件受限处理',
  },
  {
    id: 'TOOL_CMD_PROC_ENVIRON',
    category: '敏感文件访问',
    severity: 'high',
    description: '检测访问 /proc/*/environ，可能泄露进程环境变量中的凭据',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截对进程环境文件的访问，API 密钥与 token 可能因此泄露',
  },
  {
    id: 'TOOL_WEBFETCH_FILE_SCHEME',
    category: '敏感文件访问',
    severity: 'high',
    description: '检测到 WebFetch 使用非 HTTP(S) scheme，可能触发本地文件读取或 SSRF',
    tools: ['WebFetch'],
    parameter: 'url',
    remediation: '拒绝非 http/https scheme 的 fetch；本地文件请使用 Read 工具',
  },
  {
    id: 'TOOL_CMD_PRIVILEGE_ESCALATION',
    category: '权限提升',
    severity: 'critical',
    description: '检测使用 sudo、su、doas、pkexec 或 runas 进行权限提升',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '拦截操作。数字员工不应以提权身份执行命令',
  },
  {
    id: 'TOOL_CMD_UNSAFE_PERMISSIONS',
    category: '权限提升',
    severity: 'high',
    description: '检测全局权限放开（chmod 777）或设置不可变标志',
    tools: ['Bash'],
    parameter: 'command',
    remediation: '让用户确认。建议使用最小权限模型',
  },
] as const;

export const V3_SHELL_ESCAPE_RULES = [
  {
    id: 'SHELL_COMMAND_SUBSTITUTION',
    name: '命令替换',
    description: '检测反引号、$()、<()、=()、$[]、Zsh =cmd 或 PowerShell <# 等命令/进程替换语法',
  },
  {
    id: 'SHELL_OBFUSCATED_FLAGS',
    name: '混淆标志',
    description: '检测 $\'...\'、$"..."、\'\'-、""- 等特殊引用，以及被引号包裹的 flag',
  },
  {
    id: 'SHELL_BACKSLASH_WHITESPACE',
    name: '反斜杠转义空白',
    description: '检测引号外的反斜杠转义空格或 TAB，可能被解析器错误拆 token',
  },
  {
    id: 'SHELL_BACKSLASH_OPERATOR',
    name: '反斜杠转义操作符',
    description: '检测引号外反斜杠转义的 ; | & < > 等操作符；find -exec {} \\; 尾部豁免',
  },
  {
    id: 'SHELL_NEWLINES',
    name: '换行符',
    description: '检测引号外的 \\r 或换行后隐藏的第二条命令；完整 heredoc 豁免',
  },
  {
    id: 'SHELL_COMMENT_QUOTE_DESYNC',
    name: '注释引号失同步',
    description: '检测 # 注释内出现单/双引号，容易使朴素引号追踪器错位',
  },
  {
    id: 'SHELL_QUOTED_NEWLINE',
    name: '引号内换行',
    description: '检测引号内换行且下一行以 # 起始，可能在按行剥注释的解析器中隐藏参数',
  },
] as const;
